// Generated by wallpaper:posters; pinned to engine inputs at build time.
import poster0 from "./posters/butler.bloom.light.png";
import poster1 from "./posters/butler.silk.light.png";
import poster2 from "./posters/butler.riso-flow.light.png";
import poster3 from "./posters/butler.lamina.light.png";
import poster4 from "./posters/butler.diatom.light.png";
import poster5 from "./posters/butler.dusk.light.png";
import poster6 from "./posters/butler.shoreline.light.png";
import poster7 from "./posters/butler.photo-clouds.light.png";
import poster8 from "./posters/butler.photo-daisies.light.png";
import poster9 from "./posters/butler.stipple.light.png";
import poster10 from "./posters/butler.bloom.dark.png";
import poster11 from "./posters/butler.silk.dark.png";
import poster12 from "./posters/butler.riso-flow.dark.png";
import poster13 from "./posters/butler.lamina.dark.png";
import poster14 from "./posters/butler.diatom.dark.png";
import poster15 from "./posters/butler.dusk.dark.png";
import poster16 from "./posters/butler.shoreline.dark.png";
import poster17 from "./posters/butler.photo-clouds.dark.png";
import poster18 from "./posters/butler.photo-daisies.dark.png";
import poster19 from "./posters/butler.stipple.dark.png";

export const builtinPosters: Record<string, string> = {
  "butler.bloom|light": poster0,
  "butler.silk|light": poster1,
  "butler.riso-flow|light": poster2,
  "butler.lamina|light": poster3,
  "butler.diatom|light": poster4,
  "butler.dusk|light": poster5,
  "butler.shoreline|light": poster6,
  "butler.photo-clouds|light": poster7,
  "butler.photo-daisies|light": poster8,
  "butler.stipple|light": poster9,
  "butler.bloom|dark": poster10,
  "butler.silk|dark": poster11,
  "butler.riso-flow|dark": poster12,
  "butler.lamina|dark": poster13,
  "butler.diatom|dark": poster14,
  "butler.dusk|dark": poster15,
  "butler.shoreline|dark": poster16,
  "butler.photo-clouds|dark": poster17,
  "butler.photo-daisies|dark": poster18,
  "butler.stipple|dark": poster19,
};
