//! Source dashboard/handoff/roadmap rendering and optional durable view write.

use std::fs;
use std::io::Write;
use std::path::Path;

use serde_json::{Value, json};

use crate::project_ledger::events::{self, Event};
use butler_core::locale::LocaleCollation;

use super::{
    CliFailure, CommandContext, display_path, index, io_failure, now_iso, option_string,
    option_truthy, query, record,
};

/// A generated Project Ledger view.
#[derive(Clone, Copy)]
enum View {
    Dashboard,
    Handoff,
    Roadmap,
}

impl View {
    fn parse(name: &str) -> Option<Self> {
        match name {
            "dashboard" => Some(Self::Dashboard),
            "handoff" => Some(Self::Handoff),
            "roadmap" => Some(Self::Roadmap),
            _ => None,
        }
    }

    fn name(self) -> &'static str {
        match self {
            Self::Dashboard => "dashboard",
            Self::Handoff => "handoff",
            Self::Roadmap => "roadmap",
        }
    }
}

/// Whether a rendered view is only returned or also written to `views/`.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Output {
    Preview,
    Write,
}

pub(super) fn render(
    context: &CommandContext,
    options: &Value,
    collation: &LocaleCollation,
) -> Result<Value, CliFailure> {
    let name = option_string(options, "view")
        .filter(|value| !value.is_empty())
        .ok_or_else(|| {
            CliFailure::new(
                "invalid_arguments",
                "render requires dashboard, handoff, or roadmap",
            )
        })?;
    let view = View::parse(name).ok_or_else(|| {
        CliFailure::new(
            "invalid_render_view",
            format!("Unsupported render view: {name}"),
        )
    })?;
    if option_truthy(options, "write") {
        super::with_mutation_claim(&context.root, || {
            render_unlocked(&context.root, view, Output::Write, collation)
        })
    } else {
        render_unlocked(&context.root, view, Output::Preview, collation)
    }
}

fn render_unlocked(
    root: &Path,
    view: View,
    output: Output,
    collation: &LocaleCollation,
) -> Result<Value, CliFailure> {
    let index = match output {
        Output::Write => index::load_locked(root)?,
        Output::Preview => index::load(root, collation)?,
    };
    let markdown = markdown(&index, view, collation)?;
    let relative = format!("views/{}.md", view.name());
    let display = display_path(root, Path::new(&relative));
    if output == Output::Write {
        write_view(root, &relative, &display, view, &markdown)?;
    }
    Ok(
        json!({"view":view.name(),"path":display,"markdown":markdown,
        "written":output == Output::Write}),
    )
}

/// Writes the view file and records a `view_rendered` event.
fn write_view(
    root: &Path,
    relative: &str,
    display: &str,
    view: View,
    markdown: &str,
) -> Result<(), CliFailure> {
    let path = root.join(relative);
    fs::create_dir_all(path.parent().ok_or_else(io_failure)?)
        .map_err(|source| io_failure().with_source(source))?;
    fs::write(&path, markdown.as_bytes()).map_err(|source| io_failure().with_source(source))?;
    let event = Event::ViewRendered {
        r#type: "view_rendered",
        view: view.name(),
        path: display,
    };
    let mut line = events::line(&now_iso()?, event)
        .map_err(|source| io_failure().with_source(source))?
        .into_bytes();
    line.push(b'\n');
    fs::OpenOptions::new()
        .append(true)
        .open(root.join("ledger.jsonl"))
        .and_then(|mut file| file.write_all(&line))
        .map_err(|source| io_failure().with_source(source))
}

/// The reference lists the views share, at most ten entries each.
struct Sections {
    next: Vec<String>,
    blocked: Vec<String>,
    missing: Vec<String>,
    gaps: Vec<String>,
}

fn markdown(index: &Value, view: View, collation: &LocaleCollation) -> Result<String, CliFailure> {
    let generated = now_iso()?;
    let list =
        |kind: &str| query::select(index, kind, &json!({}), collation).map(|rows| refs(&rows, 10));
    let sections = Sections {
        next: list("next-actions")?,
        blocked: list("blocked")?,
        missing: list("missing-spec")?,
        gaps: list("completion-gaps")?,
    };
    let mut lines = vec!["<!-- generated by project-ledger; do not edit -->".to_owned()];
    match view {
        View::Dashboard => dashboard(&mut lines, index, &generated, &sections),
        View::Handoff => {
            lines.extend([
                "# Project Ledger Handoff".into(),
                String::new(),
                format!("Generated: {generated}"),
                String::new(),
                "## Start Here".into(),
                String::new(),
                "- Run `project-ledger status --json`.".into(),
                "- Run `project-ledger query --kind next-actions --json`.".into(),
                "- Read only referenced source records and specs.".into(),
            ]);
            section(&mut lines, "Next Actions", &sections.next);
            section(&mut lines, "Risks And Blockers", &sections.blocked);
        }
        View::Roadmap => roadmap(&mut lines, index, &generated, collation),
    }
    Ok(lines.join("\n"))
}

fn dashboard(lines: &mut Vec<String>, index: &Value, generated: &str, sections: &Sections) {
    let project = index.get("project").unwrap_or(&Value::Null);
    let counts = index.get("counts").unwrap_or(&Value::Null);
    lines.extend([
        "# Project Ledger Dashboard".into(),
        String::new(),
        format!("Generated: {generated}"),
        String::new(),
        format!(
            "Project: {} ({})",
            text(project, "name"),
            text(project, "id")
        ),
        String::new(),
        "## Counts".into(),
        String::new(),
    ]);
    for (label, key) in [
        ("Work", "work"),
        ("Tasks", "task"),
        ("Attempts", "attempt"),
        ("Decisions", "decision"),
        ("Risks", "risk"),
    ] {
        lines.push(format!(
            "- {label}: {}",
            counts.get(key).and_then(Value::as_u64).unwrap_or(0)
        ));
    }
    lines.push(format!(
        "- Issues: {}",
        index
            .get("issues")
            .and_then(Value::as_array)
            .map(Vec::len)
            .unwrap_or(0)
    ));
    section(lines, "Next Actions", &sections.next);
    section(lines, "Blocked", &sections.blocked);
    section(lines, "Missing Spec", &sections.missing);
    section(lines, "Completion Gaps", &sections.gaps);
}

fn roadmap(lines: &mut Vec<String>, index: &Value, generated: &str, collation: &LocaleCollation) {
    lines.extend([
        "# Project Ledger Roadmap".into(),
        String::new(),
        format!("Generated: {generated}"),
        String::new(),
        "## Work".into(),
        String::new(),
    ]);
    let mut work = index
        .get("records")
        .and_then(Value::as_array)
        .map(Vec::as_slice)
        .unwrap_or(&[])
        .iter()
        .filter(|record| text(record, "kind") == "work")
        .cloned()
        .collect::<Vec<_>>();
    query::sort_records(&mut work, collation);
    let refs = work
        .iter()
        .map(|record| record::reference(record, None))
        .collect::<Vec<_>>();
    lines.extend(refs.iter().map(format_ref));
    if refs.is_empty() {
        lines.push("- None".into());
    }
}

fn section(lines: &mut Vec<String>, title: &str, references: &[String]) {
    lines.extend([String::new(), format!("## {title}"), String::new()]);
    lines.extend(references.iter().cloned());
}

fn refs(value: &Value, limit: usize) -> Vec<String> {
    let rows = value.as_array().map(Vec::as_slice).unwrap_or(&[]);
    if rows.is_empty() {
        return vec!["- None".into()];
    }
    rows.iter().take(limit).map(format_ref).collect()
}

fn format_ref(value: &Value) -> String {
    format!(
        "- {} [{}] {} ({})",
        text(value, "id"),
        text(value, "status"),
        text(value, "title"),
        text(value, "path")
    )
}

fn text<'a>(value: &'a Value, key: &str) -> &'a str {
    value.get(key).and_then(Value::as_str).unwrap_or("")
}
