// Build-time assets, rendered by the same engine, clock, composition and params as picker stills.
// Run from the repository root after editing a built-in shader/default: bun run packages/butler-app/client/ui/scripts/generate-wallpaper-posters.ts.
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { createServer } from "vite";
import { chromium } from "playwright";
import { wallpaperPosterInputs } from "./wallpaper-poster-inputs";

const root = resolve(import.meta.dir, "..");
const directory = resolve(root, "src/libs/design-system/blocks/WallpaperPicker/posters");
const server = await createServer({
  root, configFile: false, server: { host: "127.0.0.1", port: 0, hmr: false, watch: null },
  optimizeDeps: { noDiscovery: true },
  resolve: { alias: { "@/butler-ds": `${root}/src/libs/design-system`, "@": `${root}/src` } },
  plugins: [{
    name: "wallpaper-poster-page",
    configureServer(server) {
      server.middlewares.use("/__posters", (_req, response) => {
        response.setHeader("Content-Type", "text/html");
        response.end("<!doctype html><title>Wallpaper posters</title>");
      });
    },
  }],
});
await server.listen();
const address = server.httpServer!.address() as { port: number };
const browser = await chromium.launch({ headless: true });
mkdirSync(directory, { recursive: true });
const entries: Record<string, string> = {};
try {
  const page = await browser.newPage();
  await page.goto(`http://127.0.0.1:${address.port}/__posters`);
  for (const tone of ["light", "dark"]) {
    const posters = await page.evaluate(async (tone) => {
      const registryPath = "/src/libs/design-system/blocks/Wallpaper/registry.ts";
      const stillPath = "/src/libs/design-system/blocks/Wallpaper/still.ts";
      const { BUILTIN_WALLPAPERS } = await import(/* @vite-ignore */ registryPath);
      const { renderWallpaperStill } = await import(/* @vite-ignore */ stillPath);
      const results = [];
      for (const module of BUILTIN_WALLPAPERS.list()) {
        if (module.manifest.image === "required" && !module.defaultImage) continue;
        const size = { width: 320, height: 200 };
        const blob = await renderWallpaperStill(module, size, tone);
        const bytes = await blob.arrayBuffer();
        const binary = Array.from(new Uint8Array(bytes), (byte) => String.fromCharCode(byte)).join("");
        results.push({ id: module.manifest.id, key: `${module.manifest.id}|${tone}`, bytes: btoa(binary) });
      }
      return results;
    }, tone);
    for (const { id, key, bytes } of posters) {
      const file = `${id}.${tone}.png`;
      writeFileSync(resolve(directory, file), Buffer.from(bytes, "base64"));
      entries[key] = file;
    }
  }
  writeFileSync(resolve(directory, "keys.json"), `${JSON.stringify(entries, null, 2)}\n`);
  const list = Object.entries(entries);
  const imports = list.map(([, file], index) => `import poster${index} from "./posters/${file}";`).join("\n");
  const values = list.map(([key], index) => `  ${JSON.stringify(key)}: poster${index},`).join("\n");
  writeFileSync(resolve(directory, "../builtinPosters.ts"), `// Generated by wallpaper:posters; pinned to engine inputs at build time.\n${imports}\n\nexport const builtinPosters: Record<string, string> = {\n${values}\n};\n`);
  writeFileSync(resolve(directory, "inputs.json"), `${JSON.stringify(wallpaperPosterInputs(root), null, 2)}\n`);
  console.log(`Generated ${Object.keys(entries).length} wallpaper posters (320x200).`);
} finally {
  await browser.close();
  await server.close();
}
