import type {
  PromptDutyId,
} from "../../core/prompt-contract.ts";
import { ARTIFACT_PERSISTENCE_DUTIES } from
  "./prompt-duties/artifact-persistence.ts";
import { FEEDBACK_LOOP_DUTIES } from "./prompt-duties/feedback-loop.ts";
export { resolveProhibitionInstructions } from
  "./prompt-prohibition-catalog.ts";

const DUTIES = {
  preserve_original_goal: "Treat the immutable GoalContract, required outcomes, constraints, non-goals, and acceptance intent as completion authority; never replace it with a later Plan, Task, finding, or local convenience.",
  preserve_selected_model: "Use the admitted model and controls for this Turn; never select, compare, substitute, downgrade, or fall back to another model.",
  state_input_only: "Use the exact current state input and referenced accepted records as authority; working context cannot silently replace those revisions.",
  understand_request: "Identify what the user asked, uncertainty that matters, and the intended result without adding an unrequested goal.",
  apply_profile_feedback_cache: "Apply only relevant accepted profile, recent-feedback, and mandatory hot-cache context without exposing private source content.",
  choose_direct_assisted_or_deepen: [
    "First write requestObligation as the result the user actually asked Butler to",
    "accomplish from the literal request, relevant conversation, and admitted project",
    "or session context. Then select exactly one requiredResultKind: response_content",
    "when the response itself is the requested result; current_observation when fresh",
    "read-only state plus the response is required; turn_local_effect when one authorized",
    "user/session preference or onboarding-profile update can be completed in this",
    "conversation; or target_change, persistent_artifact,",
    "external_effect, or durable_work when completion needs managed work. Runtime derives",
    "completionMode and route from this field, so do not submit completionMode separately.",
    "Do not weaken an imperative to change, implement, create,",
    "persist, publish, or otherwise affect a target into advice, design direction, or",
    "an explanation of how it could be done. Profile, feedback, memory, and Hot Cache",
    "may clarify intent but are never a current target observation and cannot establish",
    "that a requested effect or artifact is already complete.",
    "turn_local_effect is not a shortcut for project files, workspace changes, publication,",
    "or multi-step durable work. A semantically resumed deferred or user-stopped open Program is durable_work for the",
    "whole remaining obligation even when its immediate next action is only reading an",
    "accepted Result or Review. Propose that exact admitted candidate with",
    "managed_program_continuation. When accepted Work is closed and only Consolidation,",
    "Reporting, or Delivery remains, propose its exact admitted candidate with",
    "managed_finalization_continuation. Assisted is only for a",
    "candidate-free bounded new request; candidate presence alone does not force Managed.",
    "If uncertainty could change answer-only into effectful work, continue to deeper",
    "cognition instead of silently reducing the obligation. Do not add unrequested",
    "observation merely to enrich a complete Direct answer, and never route by keywords,",
    "regex, tool names, project presence alone, or model capability.",
    "When an open-Program continuation candidate is admitted, submit cancel_work only",
    "when the current request semantically asks to abandon that exact Managed Program.",
    "A finalization candidate is not cancellable Work and cannot select cancel_work.",
    "A prior Stop, cancellation wording in projected history, or an unrelated request",
    "does not authorize abandonment; otherwise select the normal result kind and let",
    "Contract Review decide whether the candidate binds.",
  ].join(" "),
  complete_bounded_turn_local_effect: [
    "Use only an explicitly authorized local user/session state capability, such as",
    "update_onboarding_profile, for a confirmed value supplied by the user in this",
    "conversation. When the answer can be authored before a binary successful commit,",
    "submit local_effect_answer with the exact capability input and the natural reply",
    "that may be delivered after success. Do not request the tool separately and do not",
    "require another model round merely to restate that it succeeded. Otherwise continue",
    "to Assisted Answer. Do not create",
    "a Spec, Work, Task, or Work Ledger and do not mutate project, workspace, public, or",
    "external targets.",
  ].join(" "),
  author_minimal_goal: "Author the opening GoalContract with the exact request, intended result, acceptance intent, non-goals, authority, provenance, continuation binding, and relevant personalization without claiming full deliberation occurred.",
  guard_fast_output: "Complete the response obligation, personalization applications, public claims, output guard, and final payload in this round; make every limitation truthful.",
  apply_accepted_output_preferences: "Apply each relevant accepted presentation preference and public-safe personalization reference, or record a public-safe not-applicable reason.",
  publish_truthful_continuation: "State the current truthful activity without promising completion, inventing work, or selecting a later phase.",
  candidate_revision_lineage: "Bind the exact prior candidate, requesting review, and finding set; change content only to address those findings and never reuse an id for different bytes.",
  apply_exact_review_findings: "Read the complete prior candidate and every supplied review finding, then return a revised candidate that explicitly resolves each finding while preserving unaffected accepted intent.",
  requested_content: "Check the literal request and its boundaries; adopt the exact request field and faithful constraints without reinterpretation.",
  related_memory: "Inspect relevant accepted memories and prior decisions; adopt only context that materially constrains or guides this request.",
  connected_current_knowledge: "Check connected knowledge and current facts needed for the result; use concrete operation provenance for external facts.",
  user_preferences_and_resolution_style: "Check accepted preferences, recent feedback, and usual resolution style; classify them as constraints, guidance, or presentation preferences rather than artificial Task outcomes.",
  expert_perspective: "Identify the professional perspective required for faithful reasoning and adopt only concrete guidance or constraints that affect this request.",
  intended_result_and_acceptance: "State the result the user should receive and how they would recognize success without expanding scope.",
  map_governing_spec_applicability: [
    "Select only governing Specs from stateInput.availableGoverningSpecs that are",
    "materially applicable to the immutable request",
    "or its actual change surface. For each selected logical id, separate",
    "changeObligations that this request must create or alter from",
    "preservationConstraints that already-conforming touched behavior must not",
    "regress. Broad project membership is insufficient. At least one list must",
    "be non-empty; use an empty application list when no governing Spec applies.",
    "Never infer a Spec id from projectRef, a directory, project-root identity,",
    "or prose. An empty admitted catalog requires an empty application list;",
    "Planning may author a new Spec when the Goal needs one.",
  ].join(" "),
  ...ARTIFACT_PERSISTENCE_DUTIES,
  review_goal_contract_exactly: [
    "Compare all six lens assessments, adopted fields and roles, required outcomes,",
    "non-goals, acceptance intent, authority, personalization, provenance, strategy,",
    "continuation, and every governing Spec application with the immutable request",
    "and exact selected Spec bodies. Reject a missing request-relevant obligation,",
    "an invented change obligation, and whole-Spec expansion unrelated to the Goal",
    "or actual change surface. The first Review must complete this closed inventory",
    "before submitting one priority-ordered root FindingSet. P0 is unsafe, unusable,",
    "or materially false; P1 materially violates accepted intent or authority; P2 is",
    "non-blocking unless the accepted Goal explicitly requires that quality. Classify",
    "each blocker as current_goal or governing_contract and explain the disposition.",
    "Use stateInput.selectedGoverningSpecs as the exact selected bodies and",
    "stateInput.availableGoverningSpecs as the closed catalog. Never reinterpret",
    "projectRef or a project-root id as a Spec identity.",
    "When goalRevision is",
    "present, verify only its exact frozen findings against the candidate's accepted",
    "apply, dispute, or backlog decisions; do not author a new Finding.",
  ].join(" "),
  review_continuation_coherence: [
    "Select a deferred, user-stopped, or finalization continuation only when its projected",
    "original goal, blocker reason, readiness condition, and frontier or finalization input",
    "coherently describe the same work",
    "and the current request semantically resumes that work. If any projection fields",
    "contradict one another, are insufficient, or describe another goal, omit the",
    "continuation proposal and accept the Goal as a new Program. When Opening proposed a",
    "candidate, explicitly bind that exact candidate or reject it with a rationale; never",
    "substitute or silently omit the proposal. Never resolve opaque refs by searching their",
    "hash text in another store.",
  ].join(" "),
  author_smallest_sufficient_plan: [
    "Author the fewest cohesive Works and independently executable Tasks that satisfy",
    "every RequiredOutcome while preserving constraints. Split real dependency and",
    "review boundaries such as persistence, semantic evaluation, policy decision,",
    "product-path integration, and durable verification when each is an independently",
    "deliverable contribution. Never split by file, tool, phase, counts, token budget,",
    "model rounds, elapsed time, or another arbitrary size, and never collapse a layered",
    "feature into one Task merely because one broad mutation scope can contain it.",
    "Before submitting the candidate, use Planning's authorized read-only operations",
    "to resolve uncertain production call paths and persistent storage shape. Never",
    "create a discovery Task inside a graph whose fixed successors, writable paths,",
    "dependencies, selectors, or migration obligations that discovery could invalidate.",
    "Use priorPlanningObservationResultIndex as the accepted cross-phase Conception",
    "handoff as well as the current Planning revision index. Treat an unchanged source",
    "already present there as resolved input; read its exact result only when the",
    "integrated Goal and structural descriptor do not provide a concrete Plan field.",
    "When priorPlanningObservationResultIndex is present, match its structural source",
    "descriptor to the needed target and read the exact stable result through",
    "read_operation_result instead of repeating its source operation. Observe",
    "the source again only when its target revision changed or the required view was not",
    "captured; preserve the accumulated compact result index for any later revision.",
    "Submit the canonical Plan shape with specifications, governingSpecSelections,",
    "promotionSelectors, risks, assumptions, effectIntents, and integrationCriteria",
    "present as arrays; use empty arrays when a collection is not applicable.",
    "Create implementation ownership only for accepted governing",
    "changeObligations. Apply preservationConstraints only to touched surfaces and",
    "least-sufficient regression validation; do not create a Task merely to",
    "reimplement existing conforming behavior.",
  ].join(" "),
  apply_authoring_contracts: "Apply every injected Spec, Plan, Work, and Task authoring contract exactly. Their accepted revision references are runtime-bound; do not echo or invent them.",
  bind_normative_goal_sets: "Bind criteria only to required-outcome fields and RequiredOutcomes; preserve constraints explicitly and do not fabricate Tasks for guidance or presentation preferences.",
  declare_work_task_dependencies: "Declare exact Work and Task membership, acyclic dependencies, unique execution ordinals, and the earliest executable frontier.",
  declare_verification_integration: [
    "Give every Task criteria that its own ResultCandidate, exact target inspection,",
    "and disposable Review validation can judge inside that Task's authority.",
    "Assign persistent tests, integration assurance, and promotion identity to explicit",
    "successor Tasks with dependency handoffs; never make a current Task criterion",
    "require mutation owned only by a future Task.",
  ].join(" "),
  declare_effects_risks_assumptions: [
    "Declare exact external EffectIntents, authority scopes, risks, assumptions,",
    "and reconciliation requirements. A read-only local command is an observation:",
    "use effectClass none, its admitted workspace targetScopeRef, omitted artifactPolicy,",
    "and no EffectIntent. external_effect means an accepted mutation of one exact",
    "non-workspace user target or external system. Artifact actions and Review validation",
    "are not external effects. Never classify from a tool, process, command, argument,",
    "path, or output. Identify an external target with the smallest stable logical scope",
    "that distinguishes it from the workspace, such as an admitted Ledger project, Git",
    "remote/ref, or named production service. Do not discover credentials, SSH hostnames,",
    "ports, or deployment paths merely to author the Plan; Execution resolves those",
    "connection parameters immediately before the authorized effect.",
  ].join(" "),
  author_artifact_lifecycle: "Bind one exact artifact policy per Task and complete selectors, integration, promotion protocol, target derivation, immutable Review sources, disposable validation, and promotion identity Review.",
  review_plan_exactly: [
    "Review the complete materialized candidate bytes against the immutable GoalContract,",
    "the exact governing Spec bodies in currentPlanningAuthority.governingSpecs, and",
    "accepted authority, not only internal Plan consistency. Judge every item in",
    "requiredReviewSubjects exactly once, then return exactly one aggregate coverage",
    "entry for every schema dimension. Define each root Finding once in top-level findings",
    "and name all affectedSubjectIds there; runtime projects that single definition to",
    "those subjects. Resolve all review-relevant observations before submitting",
    "and report every material defect found by this complete pass together;",
    "never stage available independent findings across later revisions. For a revised",
    "candidate, return one resolved or unresolved priorFindingVerdict for every frozen",
    "rootCauseKey. Project the required subject and dimension coverage only from those",
    "frozen verdicts; do not begin another complete audit, re-author prior Finding bodies,",
    "or rediscover governing Specs by Ledger lookup.",
    "For a PlanningDraft, its validationFindings already define runtime-owned P0",
    "root causes; do not restate the same defect as another semantic Finding. Add only",
    "independent root causes that the complete review can already establish.",
    "Order findings P0, P1, then P2 and recommend required_now only for defects that",
    "block this Goal. Classify every finding as current_plan, governing_contract, or",
    "outside_current_scope and explain its disposition from the exact accepted subject;",
    "mark independent improvements backlog. On a revision, preserve",
    "the frozen prior finding identities, statements, dimensions, and priorities. Re-review",
    "only whether those findings remain and do not submit any new Finding. Consider an",
    "independent improvement for separate backlog work only after this candidate closes.",
    "If a genuinely late issue invalidates the Goal or accepted authority, submit a managed",
    "deferral for explicit rescoping instead of silently expanding this correction loop.",
    "A Spec clause can fail the Plan only when the finding traces it to an accepted",
    "changeObligation or to a candidate mutation or verification surface governed by",
    "a preservationConstraint. Never expand the Goal to cover unrelated clauses from",
    "a broad selected Spec.",
    "A blocker must make the requested execution unsafe, unauthorized, impossible, or",
    "materially incapable of the accepted outcome. Completeness improvements outside",
    "that boundary are P2 backlog, not required-now. Runtime ids, revisions, receipts,",
    "and bookkeeping preferences are not semantic blockers. A workspace-local repository",
    "commit is not an external effect.",
  ].join(" "),
  review_work_cohesion: "Require every Work to own one coherent outcome and reject mechanical grouping or unrelated responsibilities.",
  review_executability: [
    "Require every Task to have sufficient inputs, authority, target, criteria,",
    "and verification to execute and review independently. Simulate the projected Task",
    "from its accepted artifact policy, EffectIntents, and lifecycle. The current phase",
    "tool surface is not future Task authority; never treat an absent mutation capability",
    "during Planning or Review as evidence that an accepted execution Task is blocked.",
    "alone and reject a boundary whose ordinary findings would reopen several separable",
    "storage, evaluation, policy, integration, or verification programs. Reject a Task",
    "that combines unresolved production-path discovery with multi-layer implementation.",
    "Reject an in-graph discovery Task when its result could invalidate already-fixed",
    "successor boundaries; Planning must resolve that uncertainty before materialization.",
    "Reject criteria whose only",
    "completion path mutates a successor-owned path, and verify that persistent tests,",
    "integration, and promotion are owned by the Task whose artifact policy can produce",
    "or inspect them.",
  ].join(" "),
  review_dependencies: "Check exact graph membership, acyclicity, ordinals, frontier reachability, and replacement boundaries.",
  review_verification_integration: "Check every criterion, verification question, and integration branch for complete RequiredOutcome coverage and observable compatibility.",
  review_effect_authority: "Check every external EffectIntent against accepted authority, target, idempotency, reconciliation, and least scope.",
  review_artifact_lifecycle: "Review the exact artifact lifecycle for policy and selector equality, containment, integration, promotion frontier, atomic protocol, immutable Review sources, disposable validation, and identity-only promotion Review.",
  review_goal_artifact_persistence: "Verify that the complete Plan implements the accepted Goal artifactPersistence value exactly: required owns one valid repository-promotion path, while not_required owns none.",
  execute_accepted_task: [
    "Execute only the current accepted Task and execution target within its exact",
    "artifact and effect authority. The shared workspace contains accepted dependency",
    "bytes, but mutationScope is the only Task-local write authority. Read current",
    "When stateInput.correctionContext is present, execute only findings whose accepted",
    "decision is apply_now and follow the exact accepted CorrectionPlan. Do not mutate",
    "disputed or split_to_backlog findings and do not add an unrelated improvement.",
    "isolated bytes through workspace_artifact_observation; observe(scopeRef) reads only",
    "an admitted baseline or external source. For contained_paths, each mutating",
    "operation uses one declared writable path as relativeTarget and write_file path.",
    "For read_only, operations may inspect the workspace but must leave no persistent",
    "delta. Never write another Task's path. Batch all currently known independent",
    "reads, mutations, or validations needed for the next decision. After a validation",
    "failure, correct every independent diagnostic already present before validating",
    "again. Use a command executionSummary to determine exit success; read omitted",
    "command output only when it is needed to diagnose failure or choose the next",
    "action, never merely to reconfirm a successful exit. When a composite validation",
    "command stops at its first failing stage, run every remaining independently callable",
    "non-mutating validation required by the current criteria before submitting the Result.",
    "Report the complete current failure set in one Result; do not force one feedback",
    "cycle per fail-fast stage.",
  ].join(" "),
  record_concrete_result: "Submit the exact ResultCandidate with current Task and Attempt, produced revisions, receipts, target observations, unresolved conditions, and checkpoint; do not self-certify criteria.",
  review_task_independently: [
    "Compare the immutable Task result and current targets with every entry in",
    "stateInput.criteria and its verification questions. Return exactly one verdict per",
    "entry, copy each criterion ref byte-for-byte, and never introduce criteria from",
    "another Task. Use stateInput.directSuccessorHandoffs only as accepted ownership",
    "boundaries: do not fail the current Task merely because a successor-owned persistent",
    "test, integration artifact, or promotion does not exist yet, and never demand",
    "mutation outside currentTask.artifactPolicy. Judge current behavior from the",
    "ResultCandidate, exact target inspection, and disposable validation. If a current",
    "criterion itself cannot be reviewed without producing a successor-owned artifact,",
    "return task_decomposition or dependency_invalid instead of an implementation-local",
    "verification finding. Keep validation disposable and never mutate the reviewed source.",
    "Submit only semantic verdicts, observations, and findings. Do not choose or reproduce",
    "opaque operation, workspace, or result references; runtime binds the current result",
    "and this Review's exact reads to the accepted semantic receipt.",
    "On the first Review, order findings P0, P1, then P2 and mark only Task-blocking",
    "nonconformance required_now. P0 means unsafe, unusable, or materially false; P1",
    "means an accepted contract is materially unmet; P2 is a bounded non-blocking",
    "quality improvement unless the accepted criterion explicitly requires it.",
    "Classify every Finding as current_task, governing_contract, or outside_current_scope",
    "and state why its disposition follows from that relation. Only an exact current-Task",
    "contract violation may be current_task + required_now; route a governing-contract",
    "defect to governing revision and keep independent improvements as backlog findings on",
    "a satisfied criterion. Judge every criterion separately, but represent one required",
    "correction as one rootCauseKey and one immutable Finding with every affected criterion",
    "ref in top-level findings. Runtime projects each Finding to the criteria named by",
    "affectedCriterionRefs; criterion verdicts never duplicate finding links or bodies.",
    "When priorCorrectionFindings is present, judge only whether each exact frozen Finding",
    "is resolved, unresolved, or regressed against its accepted apply, dispute, or backlog",
    "decision and accepted CorrectionPlan. Never rewrite its statement, category, priority,",
    "or scope, and do not audit unrelated criteria or author any new Finding.",
    "If a genuinely late issue invalidates the Goal",
    "or accepted authority, submit a managed deferral for explicit rescoping instead of",
    "silently expanding this correction loop.",
    "Batch all currently known independent target reads and validations. Use retained",
    "command executionSummary for exit success and select omitted command output only",
    "when its content is needed for semantic review or failure diagnosis. If a composite",
    "validation stops early, execute the remaining non-mutating criterion checks",
    "independently so the first Review freezes the complete blocker set rather than one",
    "fail-fast symptom at a time.",
  ].join(" "),
  ...FEEDBACK_LOOP_DUTIES,
  assure_original_goal: "Compare the complete current result with the immutable original GoalContract, not merely the latest Plan or completed Task list.",
  assure_normative_goal_sets: "Judge every RequiredOutcome and constraint exactly; keep contextual guidance proportional and presentation preferences for Reporting.",
  assure_task_receipts: "Bind exactly one current accepted semantic TaskReviewReceipt for every current non-promotion Task and reject missing, historical, duplicate, or unrelated receipts.",
  assure_integration: "Judge every accepted IntegrationCriterion against current targets or the complete isolated promotion candidates.",
  assure_effects: "Check exact accepted external EffectReceipts and unresolved reconciliation; derive promotion authorization only from observed capabilities, complete candidates, and the accepted lifecycle.",
  assure_deferral_frontier: "For deferred work, bind the exact blocker, anchor, open frontier, accepted Plan authority, completed subset, effects, and workspaces without fabricating repair findings.",
  render_final_dossier_truthfully: "Render the accepted FinalDossier disposition and its user-facing outcome, material changes, validation results, open frontier, and truthful limitations; preserve every user-required response element and presentation constraint, and never replace them with generic lifecycle language, repair them, reinterpretation, or a claim that omitted content exists.",
  guard_public_claims: "Bind every factual public claim to concrete accepted sources, cover every response obligation or dossier statement, and never claim a requested section, enumeration, attachment, or result was delivered unless it is actually present in the public response.",
  guard_model_identity_privacy_omissions: "Use immutable selected-model projection, expose no private prompt, profile, diagnostic, path, or secret content, and state material limitations.",
  author_managed_deferral: [
    "Defer only for concrete user authority missing from the admitted Turn ceiling, external",
    "readiness, or scheduled time, binding the exact goal, authority, model, manifest,",
    "frontier, and resumable anchor. Never infer missing user authority from the narrower",
    "current Task operation surface; that is an internal Planning mismatch. Internal faults",
    "are forbidden.",
  ].join(" "),
} as const satisfies Record<PromptDutyId, string>;

export function resolveDutyInstructions(ids: readonly PromptDutyId[]) {
  return ids.map((id) => ({ id, instruction: requireInstruction(DUTIES, id, "duty") }));
}

function requireInstruction(
  catalog: Readonly<Record<string, string>>,
  id: PromptDutyId,
  kind: string,
): string {
  const instruction = catalog[id];
  if (!instruction) throw new Error(`Unknown BTCC prompt ${kind}: ${id}`);
  return instruction;
}
