import { contentRef, type AuthoringContractBinding } from "../core/index.ts";

const COMPACT_CONTRACTS = [
  {
    contractId: "SPEC-BTCC-WORK-AUTHORING-CONTRACT",
    applicableRules: [
      "Preserve the immutable GoalContract and current governing authority.",
      "Only an accepted continuation binding authorizes reuse of a prior Program identity or frontier. Without one, treat prior Program records as context and author a new smallest sufficient Program; never reconstruct historical Task identities or normalized criterion references as current execution authority.",
      "For the first Planning of a stopped continuation whose interrupted Task already has a ResultCandidate, use the typed stopped_plan_resume submission exposed by the phase schema. Do not reproduce any Plan or Work fields. Planning re-reviews the immutable accepted Plan, and the Work Ledger carries its exact Task, Attempt, criteria, dependencies, lifecycle, and ResultCandidate directly to Task Review without another Execution. If that review requires revision, the successor Planning receives the normal complete Plan schema and must apply the frozen findings instead of resuming the rejected immutable Plan again.",
      "Treat the observable Spec catalog and selectable governing authority as different sets: governingSpecSelections may name only exact Spec revisions admitted by the GoalContract and AuthorityRevision.",
      "When project work requires a governing Spec but none is admitted, author the smallest sufficient Spec under specParentRootId; never select an observed but unaccepted catalog Spec.",
      "Every authored Spec declares parentId and concernId in reviewed bytes; use specParentRootId for a project-root Spec and an exact Spec logical id for a child.",
      "A Work is a cohesive product outcome, never a phase, file bucket, or agent assignment.",
      "A Task is the smallest independently executable and reviewable semantic contribution.",
      "Give every Task a compact displayTitle for user-facing progress: normally 8 to 24 Unicode characters in Korean or 3 to 8 short English words, never more than 32 Unicode characters. Keep the complete semantic result in intendedOutcome; never copy identifiers, Spec lists, rationale, or the full outcome into displayTitle.",
      "Split independently deliverable persistence, semantic evaluation, policy, product-path integration, and durable verification contributions by their real dependencies; never collapse a layered feature into one broad implementation Task.",
      "Task granularity is never decided by file count, path count, token budget, tool calls, model rounds, or elapsed time.",
      "Planning Review simulates each projected Task alone and rejects a boundary whose ordinary findings would reopen several separable correction programs.",
      "Planning itself resolves uncertain production call paths and persistent storage shape with authorized read-only observations before authoring the executable candidate.",
      "Reuse the accepted Conception PlanningContext observation index before new discovery. An unchanged stable source is read by exact result ref only when its compact descriptor and integrated Goal are insufficient; never repeat its source merely because Planning began.",
      "Never encode discovery as a Task inside a graph whose fixed successors, writable paths, dependencies, selectors, or migration obligations that discovery could invalidate.",
      "Submit one canonical Plan object. specifications, governingSpecSelections, promotionSelectors, risks, assumptions, effectIntents, and integrationCriteria are always arrays and are empty when not applicable.",
      "Every required Goal outcome is covered exactly by observable criteria and questions.",
      "Author one complete acyclic Work and Task graph with exact dependency order.",
      "Bind every criterion and verification question to its Goal fields and required outcome.",
      "Classify every Task by its accepted contribution. Omit artifactPolicy for non_artifact when the contribution is a transient observation, answer datum, or external fact/receipt and does not create, modify, or require versioned workspace bytes as successor or promotion lineage; omission defaults to non_artifact.",
      "Use workspace_artifact only when accepted versioned workspace bytes themselves are the Task contribution or exact review source, including read-only inspection of inherited workspace bytes required for implementation, integration, or promotion.",
      "A read-only local command that returns a transient observation uses effectClass none, the admitted workspace targetScopeRef, omitted artifactPolicy, and no EffectIntent. external_effect is reserved for an accepted mutation of one exact non-workspace user target or external system; never infer it from a tool, process, command, argument, path, or output.",
      "An external target is exact at Planning when it names the smallest stable logical target that distinguishes the effect from the workspace, such as an admitted Ledger project, Git remote/ref, or named production service. Credentials, SSH hostnames, ports, and deployment paths are execution-time connection parameters and must not trigger Planning discovery rounds.",
      "Implement the accepted Goal artifactPersistence exactly: required includes a repository-promotion Task and lifecycle; not_required includes neither.",
      "Declare task-bound external EffectIntents only for accepted external-target mutations, plus structured risks, assumptions, and exact integration criteria.",
      "Separate the shared artifact workspace from each Task's mutation authority: workspacePath names the shared baseline and promotion root, while mutationScope is read_only or exact contained writable paths.",
      "Plan paths are relative to the admitted workspace scope: use '.' for that exact root and never copy the absolute admitted workspace path into workspacePath, repository-promotion targetPath, or writablePaths.",
      "A Task that observes or extends a predecessor WorkspaceRevision remains workspace_artifact on the exact same workspacePath; dependent Tasks may and usually should have different mutationScope values.",
      "Use mutationScope read_only for verification that must inspect accepted workspace bytes without persisting changes. Use contained_paths for implementation and declare only the paths owned by that Task.",
      "Artifact lineage and Effect authority are orthogonal: a workspace_artifact/read_only Task may own one exact external EffectIntent, but a contained_paths workspace Task must remain effect-free.",
      "The workspace or writable path '.' is valid only when one cohesive outcome truly owns that complete root; never widen to it by convenience.",
      "When no repository-promotion Task exists, promotionSelectors and integrationCriteria are both empty; ordinary Task criteria own non-promotion verification.",
      "For repository change, implementation and integration Tasks share workspacePath, the repository_promotion Task uses that root as targetPath, and promotion directly depends on integration.",
      "Reporting is owned by BTCC Reporting; create a report-file Task only when a durable report artifact is an explicit Goal outcome.",
      "That shared target identifies one external baseline; Execution provisions a distinct ProgramArtifactWorkspace from it, so Planning Review must not demand different source and promotion target scopes.",
      "Each promotion selector names all implementation Tasks, its integration Task, and its promotion Task; its one integration criterion names exactly implementation plus integration as participants with the same integration and promotion ids.",
      "Each external-effect Task has an EffectIntent; a repository-promotion Task has exactly one repository_promotion EffectIntent and no other Task owns it.",
      "The Plan declares the reviewed selector, target, baseline policy, and journaled_complete_target_exchange_v1 protocol; runtime contracts own workspace provisioning, journal storage and transitions, crash reconciliation, and snapshot canonicalization, so do not re-specify them per Plan.",
      "Planning Review compares runtime-owned candidate refs and observedManifestRevision with currentPlanningAuthority; acceptedAuthority.managedBinding.expectedManifestRevision is the pre-bind lineage base, not the candidate revision.",
      "Planning Review judges the exact materialized candidate bytes against the immutable selected governing Spec bodies and returns one complete finding set covering every required review dimension.",
      "Planning Review separates complete subject coverage from root causes: one required correction has one rootCauseKey, one top-level immutable Finding, every affected subject id, the highest applicable priority, and one correction decision; runtime projects that one Finding to its affected subjects, so subjects never duplicate Finding links or bodies.",
      "A PlanningDraft validation finding is already one runtime-owned P0 root cause; Planning Review never restates that defect as a second semantic Finding and adds only independent root causes established by the same complete pass.",
      "A revised candidate is checked only against the exact frozen prior finding set and accepted finding decisions; re-review returns one resolution verdict per frozen root cause and cannot add another Finding.",
      "Implementation repair preserves the accepted graph; graph changes require governing review.",
    ],
  },
  {
    contractId: "SPEC-BTCC-WORK-LEDGER-STATE-AND-MUTATION-CONTRACT",
    applicableRules: [
      "Bind the candidate to the observed Ledger manifest revision.",
      "Only an accepted independent review may promote the exact candidate graph.",
      "Do not invent mutations, successors, or semantic defaults in storage adapters.",
    ],
  },
] as const;

export const PLANNING_AUTHORING_CONTRACTS: readonly AuthoringContractBinding[] =
  COMPACT_CONTRACTS.map((contract) => ({
    ...contract,
    revisionRef: contentRef("authoring-contract-revision", contract),
  }));
