//! Source durable-reference rules for activated BTCC databases.
use super::{StorageError, StorageResult, error};
use rusqlite::{Connection, OptionalExtension};

struct Rule {
    name: &'static str,
    from_table: &'static str,
    from_column: &'static str,
    to_table: &'static str,
    to_column: &'static str,
    filter: Option<&'static str>,
}

const RULES: &[Rule] = &[
    Rule {
        name: "turn_inbox",
        from_table: "btcc_turns",
        from_column: "inbox_id",
        to_table: "btcc_inbound_inbox",
        to_column: "inbox_id",
        filter: None,
    },
    Rule {
        name: "turn_checkpoint",
        from_table: "btcc_turns",
        from_column: "active_checkpoint_id",
        to_table: "btcc_checkpoints",
        to_column: "checkpoint_id",
        filter: None,
    },
    Rule {
        name: "turn_outbox",
        from_table: "btcc_turns",
        from_column: "delivery_outbox_id",
        to_table: "btcc_delivery_outbox",
        to_column: "outbox_id",
        filter: None,
    },
    Rule {
        name: "turn_message",
        from_table: "btcc_turns",
        from_column: "canonical_assistant_message_id",
        to_table: "btcc_messages",
        to_column: "message_id",
        filter: None,
    },
    Rule {
        name: "admission_inbox",
        from_table: "btcc_admission_claims",
        from_column: "inbox_id",
        to_table: "btcc_inbound_inbox",
        to_column: "inbox_id",
        filter: None,
    },
    Rule {
        name: "admission_owner",
        from_table: "btcc_admission_claims",
        from_column: "owner_id",
        to_table: "btcc_runtime_owners",
        to_column: "owner_id",
        filter: None,
    },
    Rule {
        name: "checkpoint_turn",
        from_table: "btcc_checkpoints",
        from_column: "turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "checkpoint_claim",
        from_table: "btcc_checkpoints",
        from_column: "active_claim_id",
        to_table: "btcc_state_claims",
        to_column: "claim_id",
        filter: None,
    },
    Rule {
        name: "state_claim_turn",
        from_table: "btcc_state_claims",
        from_column: "turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "state_claim_checkpoint",
        from_table: "btcc_state_claims",
        from_column: "checkpoint_id",
        to_table: "btcc_checkpoints",
        to_column: "checkpoint_id",
        filter: None,
    },
    Rule {
        name: "state_claim_owner",
        from_table: "btcc_state_claims",
        from_column: "owner_id",
        to_table: "btcc_runtime_owners",
        to_column: "owner_id",
        filter: None,
    },
    Rule {
        name: "outbox_turn",
        from_table: "btcc_delivery_outbox",
        from_column: "turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "delivery_turn",
        from_table: "btcc_canonical_deliveries",
        from_column: "turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "delivery_outbox",
        from_table: "btcc_canonical_deliveries",
        from_column: "outbox_id",
        to_table: "btcc_delivery_outbox",
        to_column: "outbox_id",
        filter: None,
    },
    Rule {
        name: "tool_turn",
        from_table: "btcc_guided_tool_calls",
        from_column: "turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "progress_turn",
        from_table: "btcc_progress_events",
        from_column: "turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "continuation_turn",
        from_table: "btcc_continuation_triggers",
        from_column: "turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "continuation_source_turn",
        from_table: "btcc_continuation_triggers",
        from_column: "source_turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "wake_fact_turn",
        from_table: "btcc_wake_request_facts",
        from_column: "turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "wake_fact_source_turn",
        from_table: "btcc_wake_request_facts",
        from_column: "source_turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "route_turn",
        from_table: "btcc_model_route_events",
        from_column: "turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "acceptance_turn",
        from_table: "btcc_model_round_acceptances",
        from_column: "turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "work_head",
        from_table: "btcc_guided_work_session_heads",
        from_column: "work_id",
        to_table: "btcc_guided_works",
        to_column: "work_id",
        filter: None,
    },
    Rule {
        name: "work_origin_turn",
        from_table: "btcc_guided_works",
        from_column: "origin_turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "work_current_plan",
        from_table: "btcc_guided_works",
        from_column: "current_plan_revision_id",
        to_table: "btcc_guided_work_plan_revisions",
        to_column: "plan_revision_id",
        filter: Some(r"source.scope_kind != 'project'"),
    },
    Rule {
        name: "work_binding",
        from_table: "btcc_guided_turn_work_bindings",
        from_column: "work_id",
        to_table: "btcc_guided_works",
        to_column: "work_id",
        filter: None,
    },
    Rule {
        name: "work_binding_turn",
        from_table: "btcc_guided_turn_work_bindings",
        from_column: "turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "work_plan",
        from_table: "btcc_guided_work_plan_revisions",
        from_column: "work_id",
        to_table: "btcc_guided_works",
        to_column: "work_id",
        filter: None,
    },
    Rule {
        name: "work_plan_origin_turn",
        from_table: "btcc_guided_work_plan_revisions",
        from_column: "origin_turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "work_checkpoint",
        from_table: "btcc_guided_work_checkpoint_revisions",
        from_column: "work_id",
        to_table: "btcc_guided_works",
        to_column: "work_id",
        filter: None,
    },
    Rule {
        name: "work_checkpoint_origin_turn",
        from_table: "btcc_guided_work_checkpoint_revisions",
        from_column: "origin_turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "checkpoint_plan",
        from_table: "btcc_guided_work_checkpoint_revisions",
        from_column: "plan_revision_id",
        to_table: "btcc_guided_work_plan_revisions",
        to_column: "plan_revision_id",
        filter: None,
    },
    Rule {
        name: "work_review",
        from_table: "btcc_guided_work_review_revisions",
        from_column: "work_id",
        to_table: "btcc_guided_works",
        to_column: "work_id",
        filter: None,
    },
    Rule {
        name: "work_review_origin_turn",
        from_table: "btcc_guided_work_review_revisions",
        from_column: "origin_turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "review_plan",
        from_table: "btcc_guided_work_review_revisions",
        from_column: "bound_plan_revision_id",
        to_table: "btcc_guided_work_plan_revisions",
        to_column: "plan_revision_id",
        filter: None,
    },
    Rule {
        name: "review_result",
        from_table: "btcc_guided_work_review_revisions",
        from_column: "bound_result_review_revision_id",
        to_table: "btcc_guided_work_review_revisions",
        to_column: "review_revision_id",
        filter: None,
    },
    Rule {
        name: "work_disposition",
        from_table: "btcc_guided_work_disposition_revisions",
        from_column: "work_id",
        to_table: "btcc_guided_works",
        to_column: "work_id",
        filter: None,
    },
    Rule {
        name: "work_disposition_origin_turn",
        from_table: "btcc_guided_work_disposition_revisions",
        from_column: "origin_turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "work_disposition_command",
        from_table: "btcc_guided_work_disposition_commands",
        from_column: "work_id",
        to_table: "btcc_guided_works",
        to_column: "work_id",
        filter: None,
    },
    Rule {
        name: "work_disposition_command_revision",
        from_table: "btcc_guided_work_disposition_commands",
        from_column: "disposition_revision_id",
        to_table: "btcc_guided_work_disposition_revisions",
        to_column: "disposition_revision_id",
        filter: None,
    },
    Rule {
        name: "work_closeout_diagnostic",
        from_table: "btcc_guided_work_closeout_diagnostics",
        from_column: "work_id",
        to_table: "btcc_guided_works",
        to_column: "work_id",
        filter: None,
    },
    Rule {
        name: "work_closeout_diagnostic_turn",
        from_table: "btcc_guided_work_closeout_diagnostics",
        from_column: "turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "work_mutation",
        from_table: "btcc_guided_work_mutations",
        from_column: "work_id",
        to_table: "btcc_guided_works",
        to_column: "work_id",
        filter: None,
    },
    Rule {
        name: "work_result",
        from_table: "btcc_guided_work_results",
        from_column: "work_id",
        to_table: "btcc_guided_works",
        to_column: "work_id",
        filter: None,
    },
    Rule {
        name: "work_result_origin_turn",
        from_table: "btcc_guided_work_results",
        from_column: "origin_turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "work_result_tool",
        from_table: "btcc_guided_work_results",
        from_column: "tool_call_id",
        to_table: "btcc_guided_tool_calls",
        to_column: "call_id",
        filter: None,
    },
    Rule {
        name: "effect_work",
        from_table: "btcc_guided_effects",
        from_column: "work_id",
        to_table: "btcc_guided_works",
        to_column: "work_id",
        filter: None,
    },
    Rule {
        name: "effect_plan",
        from_table: "btcc_guided_effects",
        from_column: "plan_revision_id",
        to_table: "btcc_guided_work_plan_revisions",
        to_column: "plan_revision_id",
        filter: Some(
            r"NOT EXISTS (
      SELECT 1 FROM btcc_guided_works work
      WHERE work.work_id = source.work_id AND work.scope_kind = 'project'
    )",
        ),
    },
    Rule {
        name: "effect_hint",
        from_table: "btcc_guided_effect_recovery_hints",
        from_column: "effect_id",
        to_table: "btcc_guided_effects",
        to_column: "effect_id",
        filter: None,
    },
    Rule {
        name: "effect_payload",
        from_table: "btcc_guided_effect_recovery_payloads",
        from_column: "effect_id",
        to_table: "btcc_guided_effects",
        to_column: "effect_id",
        filter: None,
    },
    Rule {
        name: "effect_blocker_work",
        from_table: "btcc_guided_work_effect_blockers",
        from_column: "work_id",
        to_table: "btcc_guided_works",
        to_column: "work_id",
        filter: None,
    },
    Rule {
        name: "effect_blocker_source_turn",
        from_table: "btcc_guided_work_effect_blockers",
        from_column: "source_turn_id",
        to_table: "btcc_turns",
        to_column: "turn_id",
        filter: None,
    },
    Rule {
        name: "legacy_import_work",
        from_table: "btcc_guided_work_legacy_imports",
        from_column: "work_id",
        to_table: "btcc_guided_works",
        to_column: "work_id",
        filter: None,
    },
];

pub(super) fn validate(db: &Connection) -> StorageResult<()> {
    for rule in RULES {
        let predicate = rule
            .filter
            .map_or(String::new(), |filter| format!("AND {filter}"));
        let sql = format!(
            "SELECT 1 FROM {from_table} AS source LEFT JOIN {to_table} AS target ON target.{to_column} = source.{from_column} WHERE source.{from_column} IS NOT NULL {predicate} AND target.{to_column} IS NULL LIMIT 1",
            from_table = rule.from_table,
            to_table = rule.to_table,
            from_column = rule.from_column,
            to_column = rule.to_column
        );
        let orphan = db
            .query_row(&sql, [], |_| Ok(()))
            .optional()
            .map_err(StorageError::sqlite)?
            .is_some();
        if orphan {
            return Err(StorageError::new(
                "agent_btcc_migration_reference_check_failed",
                format!("agent_btcc_migration_reference_check_failed:{}", rule.name),
            ));
        }
    }
    let invalid_stop = db.query_row("SELECT 1 FROM btcc_stop_requests AS stop LEFT JOIN btcc_turns AS turn ON turn.turn_id = stop.turn_id WHERE turn.turn_id IS NULL AND stop.status != 'cancelled_before_admission' LIMIT 1", [], |_| Ok(())).optional().map_err(StorageError::sqlite)?.is_some();
    if invalid_stop {
        return Err(error("agent_btcc_migration_reference_check_failed"));
    }
    Ok(())
}
