export const FEEDBACK_LOOP_DUTIES = {
  conceive_scoped_correction: [
    "Derive the smallest correction intent from the exact accepted findings and",
    "immutable GoalContract without adding unrelated work. Compare the current",
    "correctionSource semantically with stateInput.priorTaskReviewFindings for this",
    "exact Task. Decide every required finding as apply_now, dispute, or split_to_backlog",
    "with a concrete rationale; do not accept review prose automatically. Never compare",
    "by text equality, regex, category counts, or runtime judgment.",
  ].join(" "),
  classify_correction_kind: [
    "Choose implementation repair, governing revision, authority-scope revision, or",
    "pre-plan repair from semantic cause, never runtime heuristics. A current criterion",
    "or verification obligation whose remedy requires mutation owned by any other Task",
    "(predecessor, sibling, or successor) is a governing Plan, Task-decomposition, or",
    "verification-ownership defect, not an implementation repair.",
    "If materially equivalent implementation findings recur after correction, reconsider",
    "Task boundary or authority through governing Planning instead of expanding the same local repair.",
    "Use stateInput.priorTaskReviewFindings as the durable comparison input and choose",
    "governing_revision or authority_scope_revision when the recurrence exposes that boundary.",
    "When stateInput.previousFeedbackPlanningReview rejects the accepted correction kind,",
    "replace that kind in Feedback Conception before authoring another correction candidate.",
  ].join(" "),
  author_scoped_correction: "Author only records required by the accepted CorrectionScope and preserve unaffected history.",
  author_complete_impact_map: [
    "For governing or authority revision, classify every prior Task exactly once as",
    "unaffected, revalidate, rework, or replan. Preserve logical identity for",
    "unaffected and revalidate. Rework may name a replacement successor identity;",
    "replan may omit a successor when the prior Task is retired or decomposed.",
    "Unaffected means the exact accepted Task revision is carried forward by Planning;",
    "do not use unaffected when governing Spec refs, outcome, dependencies, scope,",
    "criteria, verification questions, artifact policy, effect class, Work ownership,",
    "or execution ordinal should change. Classify that Task as revalidate, rework, or",
    "replan instead.",
    "Use revalidate only when taskImpactIndex says the prior Task is accepted and has",
    "a current concrete result. A changed planned, executing, or review-failed Task",
    "requires rework or replan; it cannot be revalidated.",
    "For every revalidate impact, list revalidationPrerequisiteTaskLogicalIds explicitly.",
    "When revalidation is meant to observe a new repair, the revised Task must run after",
    "and directly depend on every listed repair Task. Use an empty list only when the",
    "accepted result can be reviewed immediately against the revised contract before any",
    "new mutation. Review this ordering semantically; prose claiming after-repair",
    "revalidation with an empty or later dependency is invalid.",
    "New successor Tasks start planned. Implementation repair changes no governing revision.",
  ].join(" "),
  review_correction_exactly: [
    "Independently review correction scope, kind, dependencies, authority, effects,",
    "impact, lifecycle change, governing links, and preserved membership against the",
    "complete direct semantic predecessors in stateInput. Their refs preserve identity;",
    "when currentResult is a workspace artifact, inspect that exact Program workspace",
    "revision rather than the external baseline target.",
    "never search digest text to rediscover an already projected body, and never create a",
    "revision finding merely because an unrelated Ledger lookup cannot recover that body.",
    "Cluster every symptom that requires the same correction under one rootCauseKey and",
    "one priority-ordered Finding. Classify it as current_correction, governing_contract,",
    "or outside_current_scope and explain why it must be fixed now or deferred. On",
    "re-review, return exactly one resolved or unresolved",
    "priorFindingVerdict for every frozen rootCauseKey without re-authoring its body or",
    "submitting a new Finding. Consider independent improvements for separate backlog work",
    "only after the current correction closes.",
  ].join(" "),
  select_correction_revision_target: [
    "When Feedback Planning needs revision, select feedback_plan only when the accepted",
    "FeedbackIntent and correction kind remain valid. Select feedback_intent when a",
    "governing-contract finding requires changing correction kind, authority scope,",
    "Task decomposition, or intended correction. This selects the semantic revision owner;",
    "it does not choose an arbitrary state-machine successor.",
  ].join(" "),
} as const;
