/** Public shared app wire-contract surface for the UI and Electron clients. */
export {
  APP_PROTOCOL_VERSION,
  WORKER_PROFILE_ID_PATTERN,
  isMessageContent,
  isProjectSourceContentPart,
  messageContentText,
} from "./message-session-contracts.ts";
export type {
  AppEventEnvelope,
  ChatKind,
  ChatSummary,
  MessageContent,
  MessageContentPart,
  ProgressDetailRow,
  ProgressSummaryRow,
  ProjectSourceContentPart,
  ProjectSourceReference,
  ProjectStatus,
  ProjectSummary,
  SessionArtifactSummary,
  SessionBranchRequest,
  SessionBranchSeed,
  SessionSummary,
  TurnState,
  WorkerActivityPhase,
  WorkerActivitySummary,
  WorkerActivityWorkBlock,
} from "./message-session-contracts.ts";

export { isSpaceCommand } from "./dashboard-space-contracts.ts";
export type {
  DashboardArtifactPage,
  DashboardBoardCard,
  DashboardBoardPage,
  DashboardBriefingContent,
  DashboardBriefingSource,
  DashboardBriefingView,
  DashboardHistoryPage,
  DashboardMaterialsPage,
  DashboardOverview,
  DashboardStatisticSeries,
  DashboardStatisticSource,
  DashboardStatisticsView,
  DashboardWorkCard,
  NavigationView,
  ProjectDashboardActivityDay,
  ProjectDashboardDocument,
  ProjectDashboardDocumentType,
  ProjectDashboardView,
  SpaceCommand,
  SpaceGroup,
  SpaceMutationResult,
  SpaceNode,
  SpaceView,
} from "./dashboard-space-contracts.ts";
