// Generates skills/butler-design-system/references/catalog.md from showcase
// meta, guidance and the viewer's "Build a screen" recipes. Modules are loaded
// by path at runtime so this file stays free of JSX for the root typecheck.
import { readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { ShowcaseGuidance, ShowcaseMeta } from "../showcase/types.ts";
import { recipeSource } from "../showcase/collectShowcaseEntries.ts";
import { SHOWCASE_BLOCK_CATEGORIES, SHOWCASE_COMPONENT_CATEGORIES } from "../showcase/categories.ts";

const designSystemRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

interface Item {
  id: string;
  name: string;
  kind: "components" | "blocks";
  meta: ShowcaseMeta;
  guidance: ShowcaseGuidance;
}

async function loadItems(): Promise<Item[]> {
  const items: Item[] = [];
  for (const kind of ["components", "blocks"] as const) {
    for (const name of readdirSync(join(designSystemRoot, kind)).sort()) {
      const folder = join(designSystemRoot, kind, name);
      if (!statSync(folder).isDirectory()) continue;
      const showcase = (await import(join(folder, `${name}.showcase.tsx`))) as { meta: ShowcaseMeta };
      const { guidance } = (await import(join(folder, `${name}.guidance.tsx`))) as { guidance: ShowcaseGuidance };
      items.push({ id: `${kind}/${name}`, name, kind, meta: showcase.meta, guidance });
    }
  }
  return items;
}

function cell(text: string): string {
  return text.replace(/\|/gu, "\\|").replace(/\n/gu, " ");
}

function itemSection(item: Item): string {
  const { guidance } = item;
  return [
    `### ${item.name}`,
    "",
    `\`import { ${item.name} } from "@/butler-ds";\` · ${item.meta.status ?? "stable"} · viewer: \`?visual=design-system&page=${item.id}\``,
    "",
    guidance.purpose,
    "",
    ...guidance.whenToUse.map((need) => `- Use for: ${need}`),
    ...guidance.whenNotToUse.map((alternative) => `- Not for: ${alternative.when} → \`${alternative.use}\``),
    `- Tokens: ${guidance.tokens.map((token) => `\`${token}\``).join(", ")}`,
    "",
  ].join("\n");
}

async function screenRecipes(): Promise<string[]> {
  const recipesPath = join(designSystemRoot, "viewer/recipes/index.ts");
  const { RECIPES } = (await import(recipesPath)) as { RECIPES: Array<{ id: string; title: string; description: string; uses: string[] }> };
  const source = readFileSync(join(designSystemRoot, "viewer/recipes/screens.tsx"), "utf8");
  return RECIPES.flatMap((recipe) => [
    `### ${recipe.title}`,
    "",
    `${recipe.description} Uses: ${recipe.uses.map((name) => `\`${name}\``).join(", ")}.`,
    "",
    "```tsx",
    recipeSource(source, recipe.title) ?? "",
    "```",
    "",
  ]);
}

export async function renderSkillCatalog(): Promise<string> {
  const items = await loadItems();
  const guide = items.flatMap((item) => [
    ...item.guidance.whenToUse.map((need) => [need, item.name, ""] as const),
    ...item.guidance.whenNotToUse.map((alternative) => [alternative.when, alternative.use, item.name] as const),
  ]).sort((left, right) => left[0].localeCompare(right[0]));
  const byCategory = (kind: Item["kind"], categories: readonly string[]) => categories.flatMap((category) => {
    const members = items.filter((item) => item.kind === kind && item.meta.category === category);
    return members.length ? [`## ${kind === "components" ? "Components" : "Blocks"} · ${category}`, "", ...members.map(itemSection)] : [];
  });
  return [
    "# Butler DS catalog",
    "",
    "<!-- Generated by `bun run ds:skill-catalog` from showcase meta, guidance and viewer recipes. Do not edit. -->",
    "",
    `${items.filter((item) => item.kind === "components").length} components and ${items.filter((item) => item.kind === "blocks").length} blocks. Every entry is a live page in the DS Viewer (\`?visual=design-system\`).`,
    "",
    "## Decision guide",
    "",
    "| I need | Use | Instead of |",
    "| --- | --- | --- |",
    ...guide.map(([need, use, from]) => `| ${cell(need)} | \`${use}\` | ${from ? `\`${from}\`` : ""} |`),
    "",
    ...byCategory("components", SHOWCASE_COMPONENT_CATEGORIES),
    ...byCategory("blocks", SHOWCASE_BLOCK_CATEGORIES),
    "## Build a screen",
    "",
    "Real Butler screens assembled only from DS pieces (no CSS files, no className, no inline styles).",
    "",
    ...(await screenRecipes()),
  ].join("\n");
}
