import { Database } from "bun:sqlite";
import type { ButlerServiceClient } from "../../../core/client.ts";
import type { SessionBindingStore } from "../../../../test-support/harness/session-store.ts";
import type { AppAutomationStore } from "../../domain/automations/automation-store.ts";
import type { AppEventStore } from "../../infrastructure/events/event-store.ts";
import type { AppTurnProgressEventStore } from "../../infrastructure/events/turn-progress-event-store.ts";
import type { AppIntegrationStore } from "../../domain/integrations/integration-store.ts";
import type { AppModelRegistryStore } from "../../domain/integrations/model-registry-store.ts";
import type { AppModelSettingsPolicy } from "../../domain/integrations/model-settings-policy.ts";
import type { AppMessageFileStore } from "../../domain/message-files/message-file-store.ts";
import type { AppProjectDashboardStore } from "../../domain/projects/project-dashboard-store.ts";
import type { AppProjectFolderStore } from "../../domain/projects/project-folder-store.ts";
import type { AppProjectStore } from "../../domain/projects/project-store.ts";
import type { AppRuntimeInfoStore } from "../../domain/runtime/runtime-info-store.ts";
import type { AppSystemMonitorStore } from "../../domain/runtime/system-monitor-store.ts";
import type { AppNavigationStore } from "../../domain/sessions/navigation-store.ts";
import type { AppNewChatBriefingStore } from "../../domain/sessions/new-chat-briefing-store.ts";
import type { AppSessionCatalogStore } from "../../domain/sessions/session-catalog-store.ts";
import type { AppSessionControlsStore } from "../../domain/sessions/session-controls-store.ts";
import type { AppConversationProjectionStore } from "../../domain/projections/app-conversation-projection-store.ts";
import type { AppSessionModuleGraph } from "../../domain/sessions/session-module-graph.ts";
import type { AppTurnRecordStore } from "../../domain/sessions/turn-record-store.ts";
import type { AppPersonalizationStore } from "../../domain/settings/personalization-store.ts";
import type { AppPreferencesStore } from "../../domain/settings/preferences-store.ts";
import type { AppSettingsPersistence } from "../../domain/settings/settings-persistence.ts";
import type { AppTransportModuleGraph } from "../../infrastructure/transport/transport-module-graph.ts";
import type { AppWorkerActivityStore } from "../../domain/workers/worker-activity-store.ts";
import type { AppWorkerControlStore } from "../../domain/workers/worker-control-store.ts";
import type { SettingsView } from "../../interface/protocol/app-protocol.ts";
import type { DeveloperLogStore } from "../../../../operations/diagnostics/developer-log-store.ts";
import type { SqliteOperationOutputReader } from "../../infrastructure/operation-output/sqlite-operation-output-reader.ts";
import type { TerminalTurnRetention } from
  "../../infrastructure/retention/terminal-turn-retention.ts";
import type { TerminalTurnRetentionQueue } from
  "../../infrastructure/retention/terminal-turn-retention-queue.ts";
import type { OwnedSqliteConnection } from
  "../../../../foundation/sqlite/owned-sqlite-connection.ts";

export interface AppStoreKernelState {
  db: Database;
  dbConnection: OwnedSqliteConnection;
  closed: boolean;
  projectWorkspaceRoot: string;
  folderSelectionSecret?: string;
  butlerData: string;
  butlerHome: string;
  appVersion?: string;
  appUpdateManifest: string;
  serverUrl: string;
  bridgeMode: SettingsView["bridge_mode"];
  serviceClient: ButlerServiceClient;
  sessionBindingStore: SessionBindingStore;
  ownsSessionBindingStore: boolean;
  runtimeInfo: AppRuntimeInfoStore;
  systemMonitor: AppSystemMonitorStore;
  developerLogs: DeveloperLogStore;
  operationOutputs: SqliteOperationOutputReader;
  terminalTurnRetention: TerminalTurnRetention;
  terminalTurnRetentionQueue: TerminalTurnRetentionQueue;
  settingsPersistence: AppSettingsPersistence;
  modelSettingsPolicy: AppModelSettingsPolicy;
  modelRegistry: AppModelRegistryStore;
  preferences: AppPreferencesStore;
  personalization: AppPersonalizationStore;
  sessionControls: AppSessionControlsStore;
  conversationProjection: AppConversationProjectionStore;
  projectFolders: AppProjectFolderStore;
  projects: AppProjectStore;
  sessionCatalog: AppSessionCatalogStore;
  navigation: AppNavigationStore;
  workers: AppWorkerActivityStore;
  workerControls: AppWorkerControlStore;
  sessionRecords: AppSessionModuleGraph["sessionRecords"];
  events: AppEventStore;
  turnProgress: AppTurnProgressEventStore;
  projectDashboard: AppProjectDashboardStore;
  contextDetails: AppSessionModuleGraph["contextDetails"];
  sessionViews: AppSessionModuleGraph["sessionViews"];
  sessionQueue: AppSessionModuleGraph["sessionQueue"];
  sessionQueueDispatcher: AppSessionModuleGraph["sessionQueueDispatcher"];
  assistantMessages: AppSessionModuleGraph["assistantMessages"];
  limitedDelivery: AppSessionModuleGraph["limitedDelivery"];
  sessionMessageProjection: AppSessionModuleGraph["sessionMessageProjection"];
  turnProgressView: AppSessionModuleGraph["turnProgressView"];
  userMessageTurns: AppSessionModuleGraph["userMessageTurns"];
  generatedSessionTitles: AppSessionModuleGraph["generatedSessionTitles"];
  newChatBriefing: AppNewChatBriefingStore;
  responderRuntime: AppSessionModuleGraph["responderRuntime"];
  systemResponderTurns: AppSessionModuleGraph["systemResponderTurns"];
  turnActions: AppSessionModuleGraph["turnActions"];
  appTransportQueue: AppTransportModuleGraph["appTransportQueue"];
  transportProjection: AppTransportModuleGraph["transportProjection"];
  transportProjectionOwner: AppTransportModuleGraph["transportProjectionOwner"];
  turns: AppTurnRecordStore;
  automationStore: AppAutomationStore;
  messageFiles: AppMessageFileStore;
  integrations: AppIntegrationStore;
}
