// Approved origin/design/settings-review ERROR_COPY, pinned for behavioral assertions.
export const ERROR_COPY: readonly { key: string; ko: string; en: string; codes?: readonly string[]; surface: string; existing?: boolean }[] = [
  { key: "settings.errors.saveFailed", ko: "저장하지 못했습니다.", en: "Couldn't save.", codes: ["invalid_settings_request", "(any PATCH /settings failure)"], surface: "toast" },
  { key: "serverErrors.settings_model_unavailable", ko: "선택한 모델을 더 이상 사용할 수 없습니다.", en: "That model is no longer available.", codes: ["settings_model_unavailable"], surface: "toast", existing: true },
  { key: "settings.mcpIdRequired", ko: "서버 ID를 입력합니다.", en: "Enter a server ID.", codes: ["mcp_server_id_required"], surface: "field", existing: true },
  { key: "settings.mcpIdInvalid", ko: "영문·숫자·점·밑줄·하이픈 1~80자로 입력합니다.", en: "Use letters, numbers, dots, underscores or hyphens (1–80).", codes: ["mcp_server_id_invalid"], surface: "field", existing: true },
  { key: "settings.mcpCommandRequired", ko: "명령을 입력합니다.", en: "Enter a command.", codes: ["mcp_command_required"], surface: "field", existing: true },
  { key: "settings.mcpUrlRequired", ko: "URL을 입력합니다.", en: "Enter a URL.", codes: ["mcp_url_required"], surface: "field", existing: true },
  { key: "settings.mcpErrors.save", ko: "서버를 저장하지 못했습니다.", en: "Couldn't save the server.", codes: ["mcp_server_save_failed", "mcp_server_update_failed", "mcp_config_invalid", "mcp_secret_unreadable"], surface: "toast" },
  { key: "settings.mcpErrors.notFound", ko: "이미 삭제된 서버입니다.", en: "This server was already removed.", codes: ["mcp_server_not_found"], surface: "toast" },
  { key: "settings.mcpErrors.unavailable", ko: "MCP 설정을 열지 못했습니다.", en: "Couldn't open MCP settings.", codes: ["mcp_registry_unavailable"], surface: "toast" },
  { key: "settings.mcpErrors.remove", ko: "서버를 삭제하지 못했습니다.", en: "Couldn't remove the server.", surface: "toast" },
  { key: "settings.mcpErrors.toggle", ko: "변경하지 못했습니다.", en: "Couldn't change it.", surface: "toast" },
  { key: "settings.mcpErrors.probe", ko: "연결을 확인하지 못했습니다.", en: "Couldn't reach the server.", surface: "toast" },
  { key: "settings.skillErrors.invalid", ko: "스킬 .zip 파일이 아닙니다.", en: "That isn't a skill .zip.", codes: ["skill_archive_invalid", "skill_archive_path_invalid", "skill_path_invalid"], surface: "field" },
  { key: "settings.skillErrors.tooLarge", ko: "파일이 너무 큽니다.", en: "That file is too large.", codes: ["skill_file_too_large"], surface: "field" },
  { key: "settings.skillErrors.import", ko: "가져오지 못했습니다.", en: "Couldn't import it.", codes: ["(other)"], surface: "field" },
  { key: "settings.security.invalidHost", ko: "호스트 이름이나 IP를 입력하세요", en: "Enter a host name or IP", surface: "field", existing: true },
  { key: "settings.wallpaper.moduleInvalid", ko: "월페이퍼 파일이 올바르지 않습니다.", en: "That wallpaper file isn't valid.", codes: ["wallpaper_module_archive_invalid", "wallpaper_module_invalid", "wallpaper_module_request_invalid"], surface: "field" },
  { key: "settings.wallpaper.moduleTooLarge", ko: "2MB 이하 모듈만 가능", en: "Modules up to 2 MB.", codes: ["wallpaper_module_archive_too_large", "wallpaper_module_file_too_large"], surface: "field", existing: true },
  { key: "settings.wallpaper.moduleExists", ko: "이미 설치된 모듈", en: "Module already installed.", codes: ["wallpaper_module_exists"], surface: "field", existing: true },
  { key: "settings.wallpaper.imageUnsupported", ko: "JPG, PNG, WebP 이미지만 가능", en: "JPG, PNG or WebP only.", codes: ["wallpaper_unsupported_type", "wallpaper_image_invalid", "wallpaper_dimensions_unsupported"], surface: "field" },
  { key: "settings.wallpaper.imageTooLarge", ko: "이미지가 너무 큽니다.", en: "That image is too large.", codes: ["wallpaper_too_large"], surface: "field" },
  { key: "settings.wallpaper.moduleImportFailed", ko: "모듈 가져오기 실패", en: "Module import failed.", codes: ["(other)"], surface: "field", existing: true },
  { key: "settings.archiveErrors.restore", ko: "복원하지 못했습니다.", en: "Couldn't restore it.", surface: "toast" },
  { key: "settings.archiveErrors.loadMore", ko: "더 불러오지 못했습니다.", en: "Couldn't load more.", surface: "toast" },
  { key: "settings.localModelErrors.discover", ko: "이 주소에서 모델을 찾지 못했습니다.", en: "No models found at this address.", codes: ["local_model_discovery_failed"], surface: "field" },
  { key: "settings.localModelErrors.register", ko: "모델을 추가하지 못했습니다.", en: "Couldn't add the model.", codes: ["local_model_registration_failed", "local_model_update_failed"], surface: "toast" },
  { key: "firstRun.keyErrors.invalid", ko: "이 키로 연결할 수 없습니다. 키를 다시 복사해 붙여 넣으세요.", en: "This key can't connect. Copy it again and paste it.", codes: ["provider_auth_error", "credential_key_invalid"], surface: "field", existing: true },
  { key: "firstRun.keyErrors.noaccess", ko: "이 키로는 모델을 쓸 수 없습니다. 결제나 사용 권한을 확인하세요.", en: "This key can't use models. Check billing or access.", codes: ["provider_permission_error", "provider_quota_exhausted"], surface: "field", existing: true },
  { key: "firstRun.keyErrors.network", ko: "서비스에 연결할 수 없습니다. 인터넷 연결을 확인하세요.", en: "Can't reach the service. Check your connection.", codes: ["provider_network_error", "provider_timeout"], surface: "field", existing: true },
  { key: "settings.grants.revokeFailed", ko: "허용을 해제하지 못했습니다.", en: "Couldn't revoke it.", codes: ["(DELETE /authority-permissions failure)"], surface: "toast" },
  { key: "settings.grants.loadFailed", ko: "허용 목록을 불러오지 못했습니다.", en: "Couldn't load approvals.", surface: "notice" },
];
