import type { ButlerToolDefinition, ToolCapabilityMetadata } from "./types.ts";
import { webSearchToolDefinition, webSearchToolMetadata } from "./web-search/index.ts";
import { webReadToolDefinition, webReadToolMetadata } from "./web-read/index.ts";
import { transformPublicDataTableToolDefinition, transformPublicDataTableToolMetadata } from "./data-table/index.ts";
import { runCommandToolDefinition, runCommandToolMetadata } from "./run-command/index.ts";
import {
  completeProjectWorkToolDefinition,
  completeProjectWorkToolMetadata,
  getWorkDashboardToolDefinition,
  getWorkDashboardToolMetadata,
  inspectProjectStatusToolDefinition,
  inspectProjectStatusToolMetadata,
  queryProjectWorkToolDefinition,
  queryProjectWorkToolMetadata,
  renderProjectDashboardToolDefinition,
  renderProjectDashboardToolMetadata,
} from "./project-ledger/index.ts";
import {
  getContextMonitorToolDefinition,
  getContextMonitorToolMetadata,
  getMemoryHealthToolDefinition,
  getMemoryHealthToolMetadata,
  getUsageMonitorToolDefinition,
  getUsageMonitorToolMetadata,
  listToolCapabilitiesToolDefinition,
  listToolCapabilitiesToolMetadata,
  readToolOutputArtifactToolDefinition,
  readToolOutputArtifactToolMetadata,
} from "./monitoring/index.ts";
import {
  callMcpToolToolDefinition,
  callMcpToolToolMetadata,
  listMcpCapabilitiesToolDefinition,
  listMcpCapabilitiesToolMetadata,
  readMcpResourceToolDefinition,
  readMcpResourceToolMetadata,
} from "./mcp/index.ts";
import {
  createAutomationToolDefinition,
  createAutomationToolMetadata,
  deleteAutomationToolDefinition,
  deleteAutomationToolMetadata,
  listAutomationsToolDefinition,
  listAutomationsToolMetadata,
  runDueAutomationsToolDefinition,
  runDueAutomationsToolMetadata,
} from "./automation/index.ts";
import {
  controlWorkToolDefinition,
  controlWorkToolMetadata,
  listTodoListToolDefinition,
  listTodoListToolMetadata,
  listWorkStreamsToolDefinition,
  listWorkStreamsToolMetadata,
  updateTodoListToolDefinition,
  updateTodoListToolMetadata,
  updateWorkStreamStateToolDefinition,
  updateWorkStreamStateToolMetadata,
} from "./work-tracking/index.ts";
import {
  ingestTaskMemoryToolDefinition,
  ingestTaskMemoryToolMetadata,
  queryMemoryToolDefinition,
  queryMemoryToolMetadata,
  readConversationContextToolDefinition,
  readConversationContextToolMetadata,
  recallMemoryToolDefinition,
  recallMemoryToolMetadata,
  summarizeUserProfileToolDefinition,
  summarizeUserProfileToolMetadata,
  updateExplicitMemoryToolDefinition,
  updateExplicitMemoryToolMetadata,
  updateOnboardingProfileToolDefinition,
  updateOnboardingProfileToolMetadata,
} from "./memory/index.ts";
import { listSkillsToolDefinition, listSkillsToolMetadata } from "./skills/index.ts";
import {
  createPlannedTaskToolDefinition,
  createPlannedTaskToolMetadata,
  repairPlannedTaskToolDefinition,
  repairPlannedTaskToolMetadata,
  requestPrincipalDecisionToolDefinition,
  requestPrincipalDecisionToolMetadata,
  reviewPlannedTaskToolDefinition,
  reviewPlannedTaskToolMetadata,
  runPlannedTaskToolDefinition,
  runPlannedTaskToolMetadata,
  writePlannedPublicReportToolDefinition,
  writePlannedPublicReportToolMetadata,
} from "./planned-task/index.ts";
import {
  dispatchWorkerToolDefinition,
  dispatchWorkerToolMetadata,
  getTaskResultToolDefinition,
  getTaskResultToolMetadata,
  listTasksToolDefinition,
  listTasksToolMetadata,
  resumeWorkerToolDefinition,
  resumeWorkerToolMetadata,
} from "./worker/index.ts";
import {
  createWorkOrchestrationToolDefinition,
  createWorkOrchestrationToolMetadata,
  runReadyWorkStreamsToolDefinition,
  runReadyWorkStreamsToolMetadata,
  syncWorkOrchestrationToolDefinition,
  syncWorkOrchestrationToolMetadata,
  writeWorkOrchestrationReportToolDefinition,
  writeWorkOrchestrationReportToolMetadata,
} from "./orchestration/index.ts";

export const CORE_BUTLER_TOOLS = [
  webSearchToolDefinition,
  webReadToolDefinition,
  transformPublicDataTableToolDefinition,
  runCommandToolDefinition,
  getWorkDashboardToolDefinition,
  inspectProjectStatusToolDefinition,
  queryProjectWorkToolDefinition,
  renderProjectDashboardToolDefinition,
  completeProjectWorkToolDefinition,
  getContextMonitorToolDefinition,
  readToolOutputArtifactToolDefinition,
  getUsageMonitorToolDefinition,
  listToolCapabilitiesToolDefinition,
  listMcpCapabilitiesToolDefinition,
  callMcpToolToolDefinition,
  readMcpResourceToolDefinition,
  createAutomationToolDefinition,
  listAutomationsToolDefinition,
  deleteAutomationToolDefinition,
  runDueAutomationsToolDefinition,
  updateTodoListToolDefinition,
  listTodoListToolDefinition,
  listWorkStreamsToolDefinition,
  updateWorkStreamStateToolDefinition,
  controlWorkToolDefinition,
  getMemoryHealthToolDefinition,
  ingestTaskMemoryToolDefinition,
  recallMemoryToolDefinition,
  queryMemoryToolDefinition,
  summarizeUserProfileToolDefinition,
  updateOnboardingProfileToolDefinition,
  readConversationContextToolDefinition,
  updateExplicitMemoryToolDefinition,
  listSkillsToolDefinition,
  dispatchWorkerToolDefinition,
  createPlannedTaskToolDefinition,
  runPlannedTaskToolDefinition,
  reviewPlannedTaskToolDefinition,
  repairPlannedTaskToolDefinition,
  requestPrincipalDecisionToolDefinition,
  writePlannedPublicReportToolDefinition,
  resumeWorkerToolDefinition,
  createWorkOrchestrationToolDefinition,
  runReadyWorkStreamsToolDefinition,
  syncWorkOrchestrationToolDefinition,
  writeWorkOrchestrationReportToolDefinition,
  listTasksToolDefinition,
  getTaskResultToolDefinition,
] satisfies ButlerToolDefinition[];

export const BUTLER_TOOLS = CORE_BUTLER_TOOLS;

export const TOOL_CAPABILITY_METADATA: Record<string, ToolCapabilityMetadata> = {
  [webSearchToolDefinition.name]: webSearchToolMetadata,
  [webReadToolDefinition.name]: webReadToolMetadata,
  [transformPublicDataTableToolDefinition.name]: transformPublicDataTableToolMetadata,
  [runCommandToolDefinition.name]: runCommandToolMetadata,
  [getWorkDashboardToolDefinition.name]: getWorkDashboardToolMetadata,
  [inspectProjectStatusToolDefinition.name]: inspectProjectStatusToolMetadata,
  [queryProjectWorkToolDefinition.name]: queryProjectWorkToolMetadata,
  [renderProjectDashboardToolDefinition.name]: renderProjectDashboardToolMetadata,
  [completeProjectWorkToolDefinition.name]: completeProjectWorkToolMetadata,
  [getContextMonitorToolDefinition.name]: getContextMonitorToolMetadata,
  [readToolOutputArtifactToolDefinition.name]: readToolOutputArtifactToolMetadata,
  [getUsageMonitorToolDefinition.name]: getUsageMonitorToolMetadata,
  [listToolCapabilitiesToolDefinition.name]: listToolCapabilitiesToolMetadata,
  [listMcpCapabilitiesToolDefinition.name]: listMcpCapabilitiesToolMetadata,
  [callMcpToolToolDefinition.name]: callMcpToolToolMetadata,
  [readMcpResourceToolDefinition.name]: readMcpResourceToolMetadata,
  [createAutomationToolDefinition.name]: createAutomationToolMetadata,
  [listAutomationsToolDefinition.name]: listAutomationsToolMetadata,
  [deleteAutomationToolDefinition.name]: deleteAutomationToolMetadata,
  [runDueAutomationsToolDefinition.name]: runDueAutomationsToolMetadata,
  [updateTodoListToolDefinition.name]: updateTodoListToolMetadata,
  [listTodoListToolDefinition.name]: listTodoListToolMetadata,
  [listWorkStreamsToolDefinition.name]: listWorkStreamsToolMetadata,
  [updateWorkStreamStateToolDefinition.name]: updateWorkStreamStateToolMetadata,
  [controlWorkToolDefinition.name]: controlWorkToolMetadata,
  [getMemoryHealthToolDefinition.name]: getMemoryHealthToolMetadata,
  [ingestTaskMemoryToolDefinition.name]: ingestTaskMemoryToolMetadata,
  [recallMemoryToolDefinition.name]: recallMemoryToolMetadata,
  [queryMemoryToolDefinition.name]: queryMemoryToolMetadata,
  [summarizeUserProfileToolDefinition.name]: summarizeUserProfileToolMetadata,
  [updateOnboardingProfileToolDefinition.name]: updateOnboardingProfileToolMetadata,
  [readConversationContextToolDefinition.name]: readConversationContextToolMetadata,
  [updateExplicitMemoryToolDefinition.name]: updateExplicitMemoryToolMetadata,
  [listSkillsToolDefinition.name]: listSkillsToolMetadata,
  [dispatchWorkerToolDefinition.name]: dispatchWorkerToolMetadata,
  [createPlannedTaskToolDefinition.name]: createPlannedTaskToolMetadata,
  [runPlannedTaskToolDefinition.name]: runPlannedTaskToolMetadata,
  [reviewPlannedTaskToolDefinition.name]: reviewPlannedTaskToolMetadata,
  [repairPlannedTaskToolDefinition.name]: repairPlannedTaskToolMetadata,
  [requestPrincipalDecisionToolDefinition.name]: requestPrincipalDecisionToolMetadata,
  [writePlannedPublicReportToolDefinition.name]: writePlannedPublicReportToolMetadata,
  [resumeWorkerToolDefinition.name]: resumeWorkerToolMetadata,
  [createWorkOrchestrationToolDefinition.name]: createWorkOrchestrationToolMetadata,
  [runReadyWorkStreamsToolDefinition.name]: runReadyWorkStreamsToolMetadata,
  [syncWorkOrchestrationToolDefinition.name]: syncWorkOrchestrationToolMetadata,
  [writeWorkOrchestrationReportToolDefinition.name]: writeWorkOrchestrationReportToolMetadata,
  [listTasksToolDefinition.name]: listTasksToolMetadata,
  [getTaskResultToolDefinition.name]: getTaskResultToolMetadata,
};
