import type { ProviderModelMetadata, ReasoningEffort } from "../model-catalog.ts";

export const OPENAI_SOURCE = "https://developers.openai.com/api/docs/models/compare";

const DEFAULT_REASONING_EFFORT: ReasoningEffort = "xhigh";
const GPT_56_REASONING_EFFORTS: ReasoningEffort[] = ["none", "low", "medium", "high", "xhigh", "max"];
const GPT_55_REASONING_EFFORTS: ReasoningEffort[] = ["none", "low", "medium", "high", "xhigh"];

export const OPENAI_MODELS: readonly ProviderModelMetadata[] = [
  {
    provider_id: "openai",
    provider_label: "OpenAI",
    model_id: "gpt-5.6-sol",
    model_ref: "openai/gpt-5.6-sol",
    display_name: "GPT-5.6 Sol",
    status: "latest",
    context_window_tokens: 1_050_000,
    max_output_tokens: 128_000,
    default_reasoning_effort: DEFAULT_REASONING_EFFORT,
    reasoning_efforts: GPT_56_REASONING_EFFORTS,
    token_estimator: "openai_tiktoken_o200k",
    source_url: OPENAI_SOURCE,
    runtime_supported: true,
  },
  {
    provider_id: "openai",
    provider_label: "OpenAI",
    model_id: "gpt-5.6-terra",
    model_ref: "openai/gpt-5.6-terra",
    display_name: "GPT-5.6 Terra",
    status: "recommended",
    context_window_tokens: 1_050_000,
    max_output_tokens: 128_000,
    default_reasoning_effort: "medium",
    reasoning_efforts: GPT_56_REASONING_EFFORTS,
    token_estimator: "openai_tiktoken_o200k",
    source_url: OPENAI_SOURCE,
    runtime_supported: true,
  },
  {
    provider_id: "openai",
    provider_label: "OpenAI",
    model_id: "gpt-5.6-luna",
    model_ref: "openai/gpt-5.6-luna",
    display_name: "GPT-5.6 Luna",
    status: "available",
    context_window_tokens: 1_050_000,
    max_output_tokens: 128_000,
    default_reasoning_effort: "medium",
    reasoning_efforts: GPT_56_REASONING_EFFORTS,
    token_estimator: "openai_tiktoken_o200k",
    source_url: OPENAI_SOURCE,
    runtime_supported: true,
  },
  {
    provider_id: "openai",
    provider_label: "OpenAI",
    model_id: "gpt-5.5",
    model_ref: "openai/gpt-5.5",
    // The Codex subscription carrier historically persisted this alias. Keep
    // it explicit so old settings remain identifiable without selecting a
    // newer OpenAI model by accident.
    aliases: ["gpt-5.5", "gpt-5.5-codex", "openai/gpt-5.5-codex"],
    display_name: "GPT-5.5",
    status: "available",
    context_window_tokens: 1_050_000,
    max_output_tokens: 128_000,
    default_reasoning_effort: DEFAULT_REASONING_EFFORT,
    reasoning_efforts: GPT_55_REASONING_EFFORTS,
    token_estimator: "openai_tiktoken_o200k",
    source_url: OPENAI_SOURCE,
    runtime_supported: true,
  },
  {
    provider_id: "openai",
    provider_label: "OpenAI",
    model_id: "gpt-5.4",
    model_ref: "openai/gpt-5.4",
    display_name: "GPT-5.4",
    status: "available",
    context_window_tokens: 1_050_000,
    max_output_tokens: 128_000,
    default_reasoning_effort: "medium",
    reasoning_efforts: GPT_55_REASONING_EFFORTS,
    token_estimator: "openai_tiktoken_o200k",
    source_url: OPENAI_SOURCE,
    runtime_supported: true,
  },
  {
    provider_id: "openai",
    provider_label: "OpenAI",
    model_id: "gpt-5.4-mini",
    model_ref: "openai/gpt-5.4-mini",
    display_name: "GPT-5.4 Mini",
    status: "available",
    context_window_tokens: 400_000,
    max_output_tokens: 128_000,
    default_reasoning_effort: "medium",
    reasoning_efforts: GPT_55_REASONING_EFFORTS,
    token_estimator: "openai_tiktoken_o200k",
    source_url: OPENAI_SOURCE,
    runtime_supported: true,
  },
  {
    provider_id: "openai",
    provider_label: "OpenAI",
    model_id: "gpt-5.4-nano",
    model_ref: "openai/gpt-5.4-nano",
    display_name: "GPT-5.4 Nano",
    status: "available",
    context_window_tokens: 400_000,
    max_output_tokens: 128_000,
    default_reasoning_effort: "medium",
    reasoning_efforts: GPT_55_REASONING_EFFORTS,
    token_estimator: "openai_tiktoken_o200k",
    source_url: OPENAI_SOURCE,
    runtime_supported: true,
  },
];
