//! Source dashboard/handoff/roadmap rendering and optional durable view write.

use std::fs;
use std::io::Write;
use std::path::Path;

use serde_json::{Value, json};

use crate::locale::LocaleCollation;

use super::{
    CliFailure, CommandContext, display_path, index, io_failure, now_iso, option_string,
    option_truthy, query, record,
};

pub(super) fn render(
    context: &CommandContext,
    options: &Value,
    collation: &LocaleCollation,
) -> Result<Value, CliFailure> {
    let view = option_string(options, "view")
        .filter(|value| !value.is_empty())
        .ok_or_else(|| {
            CliFailure::new(
                "invalid_arguments",
                "render requires dashboard, handoff, or roadmap",
            )
        })?;
    if !matches!(view, "dashboard" | "handoff" | "roadmap") {
        return Err(CliFailure::new(
            "invalid_render_view",
            format!("Unsupported render view: {view}"),
        ));
    }
    if option_truthy(options, "write") {
        super::with_mutation_claim(&context.root, || {
            render_unlocked(&context.root, view, true, collation)
        })
    } else {
        render_unlocked(&context.root, view, false, collation)
    }
}

fn render_unlocked(
    root: &Path,
    view: &str,
    write: bool,
    collation: &LocaleCollation,
) -> Result<Value, CliFailure> {
    let index = if write {
        index::load_locked(root)?
    } else {
        index::load(root, collation)?
    };
    let markdown = markdown(&index, view, collation)?;
    let relative = format!("views/{view}.md");
    let path = root.join(&relative);
    let display = display_path(root, Path::new(&relative));
    if write {
        fs::create_dir_all(path.parent().ok_or_else(io_failure)?).map_err(|_| io_failure())?;
        fs::write(&path, markdown.as_bytes()).map_err(|_| io_failure())?;
        let event = json!({
            "schema":"project-ledger.event.v1","ts":now_iso()?,
            "type":"view_rendered","view":view,"path":display,"source":"project-ledger",
        });
        let mut line = crate::json::stringify(&event)
            .map_err(|_| io_failure())?
            .into_bytes();
        line.push(b'\n');
        fs::OpenOptions::new()
            .append(true)
            .open(root.join("ledger.jsonl"))
            .and_then(|mut file| file.write_all(&line))
            .map_err(|_| io_failure())?;
    }
    Ok(json!({"view":view,"path":display,"markdown":markdown,"written":write}))
}

fn markdown(index: &Value, view: &str, collation: &LocaleCollation) -> Result<String, CliFailure> {
    let generated = now_iso()?;
    let next = refs(
        &query::select(index, "next-actions", &json!({}), collation)?,
        10,
    );
    let blocked = refs(&query::select(index, "blocked", &json!({}), collation)?, 10);
    let missing = refs(
        &query::select(index, "missing-spec", &json!({}), collation)?,
        10,
    );
    let gaps = refs(
        &query::select(index, "completion-gaps", &json!({}), collation)?,
        10,
    );
    let mut lines = vec!["<!-- generated by project-ledger; do not edit -->".to_owned()];
    match view {
        "dashboard" => {
            let project = index.get("project").unwrap_or(&Value::Null);
            let counts = index.get("counts").unwrap_or(&Value::Null);
            lines.extend([
                "# Project Ledger Dashboard".into(),
                String::new(),
                format!("Generated: {generated}"),
                String::new(),
                format!(
                    "Project: {} ({})",
                    text(project, "name"),
                    text(project, "id")
                ),
                String::new(),
                "## Counts".into(),
                String::new(),
            ]);
            for (label, key) in [
                ("Work", "work"),
                ("Tasks", "task"),
                ("Attempts", "attempt"),
                ("Decisions", "decision"),
                ("Risks", "risk"),
            ] {
                lines.push(format!(
                    "- {label}: {}",
                    counts.get(key).and_then(Value::as_u64).unwrap_or(0)
                ));
            }
            lines.push(format!(
                "- Issues: {}",
                index
                    .get("issues")
                    .and_then(Value::as_array)
                    .map(Vec::len)
                    .unwrap_or(0)
            ));
            section(&mut lines, "Next Actions", &next);
            section(&mut lines, "Blocked", &blocked);
            section(&mut lines, "Missing Spec", &missing);
            section(&mut lines, "Completion Gaps", &gaps);
        }
        "handoff" => {
            lines.extend([
                "# Project Ledger Handoff".into(),
                String::new(),
                format!("Generated: {generated}"),
                String::new(),
                "## Start Here".into(),
                String::new(),
                "- Run `project-ledger status --json`.".into(),
                "- Run `project-ledger query --kind next-actions --json`.".into(),
                "- Read only referenced source records and specs.".into(),
            ]);
            section(&mut lines, "Next Actions", &next);
            section(&mut lines, "Risks And Blockers", &blocked);
        }
        "roadmap" => {
            lines.extend([
                "# Project Ledger Roadmap".into(),
                String::new(),
                format!("Generated: {generated}"),
                String::new(),
                "## Work".into(),
                String::new(),
            ]);
            let mut work = index
                .get("records")
                .and_then(Value::as_array)
                .map(Vec::as_slice)
                .unwrap_or(&[])
                .iter()
                .filter(|record| text(record, "kind") == "work")
                .cloned()
                .collect::<Vec<_>>();
            query::sort_records(&mut work, collation);
            let refs = work
                .iter()
                .map(|record| record::reference(record, None))
                .collect::<Vec<_>>();
            lines.extend(refs.iter().map(format_ref));
            if refs.is_empty() {
                lines.push("- None".into());
            }
        }
        _ => {
            return Err(CliFailure::new(
                "invalid_render_view",
                format!("Unsupported render view: {view}"),
            ));
        }
    }
    Ok(lines.join("\n"))
}

fn section(lines: &mut Vec<String>, title: &str, references: &[String]) {
    lines.extend([String::new(), format!("## {title}"), String::new()]);
    lines.extend(references.iter().cloned());
}

fn refs(value: &Value, limit: usize) -> Vec<String> {
    let rows = value.as_array().map(Vec::as_slice).unwrap_or(&[]);
    if rows.is_empty() {
        return vec!["- None".into()];
    }
    rows.iter().take(limit).map(format_ref).collect()
}

fn format_ref(value: &Value) -> String {
    format!(
        "- {} [{}] {} ({})",
        text(value, "id"),
        text(value, "status"),
        text(value, "title"),
        text(value, "path")
    )
}

fn text<'a>(value: &'a Value, key: &str) -> &'a str {
    value.get(key).and_then(Value::as_str).unwrap_or("")
}
