import type { ShowcaseCategory } from "./categories";

// Temporary IA placement for folders that do not have a `*.showcase.tsx` yet.
// Remove an entry when its showcase file declares `meta.category` itself.
export const legacyShowcaseCategories: Record<string, ShowcaseCategory> = {
  "components/Breadcrumb": "Navigation",
  "components/ButtonContainer": "Action",
  "components/Card": "Layout",
  "components/Chart": "Data display",
  "components/Clickable": "Action",
  "components/ColorSwatchInput": "Input",
  "components/ContextMenu": "Overlay",
  "components/Dialog": "Overlay",
  "components/DropdownMenu": "Overlay",
  "components/Field": "Input",
  "components/IconButton": "Action",
  "components/Icons": "Data display",
  "components/InlineReference": "Data display",
  "components/Input": "Input",
  "components/Label": "Input",
  "components/NativeSelect": "Input",
  "components/PillButton": "Action",
  "components/Popover": "Overlay",
  "components/RollingStatusLine": "Feedback",
  "components/RollingSwap": "Feedback",
  "components/Section": "Layout",
  "components/Separator": "Layout",
  "components/Skeleton": "Feedback",
  "components/Slider": "Input",
  "components/Space": "Layout",
  "components/Spinner": "Feedback",
  "components/Switch": "Input",
  "components/Tabs": "Navigation",
  "components/Tag": "Data display",
  "components/Textarea": "Input",
  "components/TintedGlass": "Layout",
  "components/Toast": "Feedback",
  "components/Tooltip": "Overlay",
  "blocks/ActivityFeed": "Conversation & Activity",
  "blocks/ActivityHeatmap": "Dashboard & Metrics",
  "blocks/AdaptiveShell": "Shell",
  "blocks/ArtifactList": "Documents & Artifacts",
  "blocks/ArtifactPreview": "Documents & Artifacts",
  "blocks/AttachmentList": "Composer",
  "blocks/AutomationRow": "Dashboard & Metrics",
  "blocks/AutomationRunList": "Dashboard & Metrics",
  "blocks/CardList": "Settings & Forms",
  "blocks/ChangedLineDiff": "Conversation & Activity",
  "blocks/ChromeFrame": "Shell",
  "blocks/CollapsibleNavGroup": "Navigation",
  "blocks/CommandPanel": "Navigation",
  "blocks/ComposerAdjunctPanel": "Composer",
  "blocks/ComposerCard": "Composer",
  "blocks/ComposerControl": "Composer",
  "blocks/ComposerQueuePanel": "Composer",
  "blocks/ContextDonutButton": "Composer",
  "blocks/ConversationShell": "Conversation & Activity",
  "blocks/DashboardHeader": "Dashboard & Metrics",
  "blocks/DialogForm": "Settings & Forms",
  "blocks/DisclosureRow": "Conversation & Activity",
  "blocks/DocumentReader": "Documents & Artifacts",
  "blocks/DocumentTile": "Documents & Artifacts",
  "blocks/EmptyLine": "Conversation & Activity",
  "blocks/FilteredSelectPopover": "Navigation",
  "blocks/FormRow": "Settings & Forms",
  "blocks/FormSection": "Settings & Forms",
  "blocks/InspectorPanel": "Inspector",
  "blocks/InspectorShell": "Inspector",
  "blocks/KeyValueRow": "Inspector",
  "blocks/ListRow": "Navigation",
  "blocks/ManagementPage": "Shell",
  "blocks/MarkdownContent": "Documents & Artifacts",
  "blocks/MessageAvatarBlock": "Conversation & Activity",
  "blocks/MessageRow": "Conversation & Activity",
  "blocks/MetricCard": "Dashboard & Metrics",
  "blocks/MetricGrid": "Dashboard & Metrics",
  "blocks/NavRow": "Navigation",
  "blocks/NavSection": "Navigation",
  "blocks/Notice": "Feedback",
  "blocks/OptionMenu": "Navigation",
  "blocks/OverflowActionMenu": "Navigation",
  "blocks/PanelHeader": "Shell",
  "blocks/PercentInputControl": "Settings & Forms",
  "blocks/ProgressMeter": "Inspector",
  "blocks/ProgressStepper": "Inspector",
  "blocks/PromptSuggestionList": "Composer",
  "blocks/ResourceSummary": "Dashboard & Metrics",
  "blocks/ResourceTile": "Dashboard & Metrics",
  "blocks/RowActionCluster": "Navigation",
  "blocks/ScrollArea": "Shell",
  "blocks/SessionRow": "Navigation",
  "blocks/SettingsField": "Settings & Forms",
  "blocks/SettingsHeader": "Settings & Forms",
  "blocks/SettingsNav": "Settings & Forms",
  "blocks/SettingsSecretRows": "Settings & Forms",
  "blocks/SettingsShell": "Settings & Forms",
  "blocks/SetupWizardShell": "Shell",
  "blocks/SidebarShell": "Shell",
  "blocks/SortableCardList": "Settings & Forms",
  "blocks/SurfacePanel": "Shell",
  "blocks/TitlebarShell": "Shell",
  "blocks/TodoProgressPanel": "Conversation & Activity",
  "blocks/TokenInputControl": "Settings & Forms",
  "blocks/WorkActivityBlock": "Conversation & Activity",
  "blocks/WorkerActivityPanel": "Conversation & Activity",
  "blocks/WorkerActivityRow": "Conversation & Activity",
};
