import type { ShowcaseCategory } from "./categories";

// Temporary IA placement for folders that do not have a `*.showcase.tsx` yet.
// Remove an entry when its showcase file declares `meta.category` itself.
export const legacyShowcaseCategories: Record<string, ShowcaseCategory> = {
  "blocks/ActivityFeed": "Conversation & Activity",
  "blocks/ActivityHeatmap": "Dashboard & Metrics",
  "blocks/AdaptiveShell": "Shell",
  "blocks/ArtifactList": "Documents & Artifacts",
  "blocks/ArtifactPreview": "Documents & Artifacts",
  "blocks/AttachmentList": "Composer",
  "blocks/AutomationRow": "Dashboard & Metrics",
  "blocks/AutomationRunList": "Dashboard & Metrics",
  "blocks/CardList": "Settings & Forms",
  "blocks/ChangedLineDiff": "Conversation & Activity",
  "blocks/CollapsibleNavGroup": "Navigation",
  "blocks/ComposerAdjunctPanel": "Composer",
  "blocks/ComposerCard": "Composer",
  "blocks/DashboardHeader": "Dashboard & Metrics",
  "blocks/DialogForm": "Settings & Forms",
  "blocks/DisclosureRow": "Conversation & Activity",
  "blocks/DocumentReader": "Documents & Artifacts",
  "blocks/DocumentTile": "Documents & Artifacts",
  "blocks/EmptyLine": "Conversation & Activity",
  "blocks/FilteredSelectPopover": "Navigation",
  "blocks/FormRow": "Settings & Forms",
  "blocks/InspectorPanel": "Inspector",
  "blocks/InspectorShell": "Inspector",
  "blocks/KeyValueRow": "Inspector",
  "blocks/ListRow": "Navigation",
  "blocks/MarkdownContent": "Documents & Artifacts",
  "blocks/MessageAvatarBlock": "Conversation & Activity",
  "blocks/NavRow": "Navigation",
  "blocks/NavSection": "Navigation",
  "blocks/Notice": "Feedback",
  "blocks/OptionMenu": "Navigation",
  "blocks/OverflowActionMenu": "Navigation",
  "blocks/PanelHeader": "Shell",
  "blocks/PercentInputControl": "Settings & Forms",
  "blocks/ProgressStepper": "Inspector",
  "blocks/ResourceSummary": "Dashboard & Metrics",
  "blocks/ResourceTile": "Dashboard & Metrics",
  "blocks/RowActionCluster": "Navigation",
  "blocks/ScrollArea": "Shell",
  "blocks/SessionRow": "Navigation",
  "blocks/SettingsHeader": "Settings & Forms",
  "blocks/SettingsNav": "Settings & Forms",
  "blocks/SettingsSecretRows": "Settings & Forms",
  "blocks/SurfacePanel": "Shell",
  "blocks/TitlebarShell": "Shell",
  "blocks/TodoProgressPanel": "Conversation & Activity",
  "blocks/TokenInputControl": "Settings & Forms",
  "blocks/WorkerActivityPanel": "Conversation & Activity",
};
